// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: qms_addons.proto
// Protobuf Java Version: 4.31.1

package org.cyverse.de.protobufs;

@com.google.protobuf.Generated
public interface AddonRateListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:qms.AddonRateList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Can contain telemetry data.
   * </pre>
   *
   * <code>.header.Header header = 1;</code>
   * @return Whether the header field is set.
   */
  boolean hasHeader();
  /**
   * <pre>
   * Can contain telemetry data.
   * </pre>
   *
   * <code>.header.Header header = 1;</code>
   * @return The header.
   */
  org.cyverse.de.protobufs.Header getHeader();
  /**
   * <pre>
   * Can contain telemetry data.
   * </pre>
   *
   * <code>.header.Header header = 1;</code>
   */
  org.cyverse.de.protobufs.HeaderOrBuilder getHeaderOrBuilder();

  /**
   * <pre>
   * Contains error info from the request handler.
   * </pre>
   *
   * <code>.svcerror.ServiceError error = 2;</code>
   * @return Whether the error field is set.
   */
  boolean hasError();
  /**
   * <pre>
   * Contains error info from the request handler.
   * </pre>
   *
   * <code>.svcerror.ServiceError error = 2;</code>
   * @return The error.
   */
  org.cyverse.de.protobufs.ServiceError getError();
  /**
   * <pre>
   * Contains error info from the request handler.
   * </pre>
   *
   * <code>.svcerror.ServiceError error = 2;</code>
   */
  org.cyverse.de.protobufs.ServiceErrorOrBuilder getErrorOrBuilder();

  /**
   * <pre>
   * The list of addon rate objects returned by the request handler.
   * </pre>
   *
   * <code>repeated .qms.AddonRate addon_rates = 3 [json_name = "addon_rates"];</code>
   */
  java.util.List<org.cyverse.de.protobufs.AddonRate> 
      getAddonRatesList();
  /**
   * <pre>
   * The list of addon rate objects returned by the request handler.
   * </pre>
   *
   * <code>repeated .qms.AddonRate addon_rates = 3 [json_name = "addon_rates"];</code>
   */
  org.cyverse.de.protobufs.AddonRate getAddonRates(int index);
  /**
   * <pre>
   * The list of addon rate objects returned by the request handler.
   * </pre>
   *
   * <code>repeated .qms.AddonRate addon_rates = 3 [json_name = "addon_rates"];</code>
   */
  int getAddonRatesCount();
  /**
   * <pre>
   * The list of addon rate objects returned by the request handler.
   * </pre>
   *
   * <code>repeated .qms.AddonRate addon_rates = 3 [json_name = "addon_rates"];</code>
   */
  java.util.List<? extends org.cyverse.de.protobufs.AddonRateOrBuilder> 
      getAddonRatesOrBuilderList();
  /**
   * <pre>
   * The list of addon rate objects returned by the request handler.
   * </pre>
   *
   * <code>repeated .qms.AddonRate addon_rates = 3 [json_name = "addon_rates"];</code>
   */
  org.cyverse.de.protobufs.AddonRateOrBuilder getAddonRatesOrBuilder(
      int index);
}
