// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: analysis_requests.proto

package org.cyverse.de.protobufs;

public interface AnalysisRecordListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:debuff.AnalysisRecordList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.debuff.Header header = 1;</code>
   * @return Whether the header field is set.
   */
  boolean hasHeader();
  /**
   * <code>.debuff.Header header = 1;</code>
   * @return The header.
   */
  org.cyverse.de.protobufs.Header getHeader();
  /**
   * <code>.debuff.Header header = 1;</code>
   */
  org.cyverse.de.protobufs.HeaderOrBuilder getHeaderOrBuilder();

  /**
   * <code>repeated .debuff.AnalysisRecord analyses = 2;</code>
   */
  java.util.List<org.cyverse.de.protobufs.AnalysisRecord> 
      getAnalysesList();
  /**
   * <code>repeated .debuff.AnalysisRecord analyses = 2;</code>
   */
  org.cyverse.de.protobufs.AnalysisRecord getAnalyses(int index);
  /**
   * <code>repeated .debuff.AnalysisRecord analyses = 2;</code>
   */
  int getAnalysesCount();
  /**
   * <code>repeated .debuff.AnalysisRecord analyses = 2;</code>
   */
  java.util.List<? extends org.cyverse.de.protobufs.AnalysisRecordOrBuilder> 
      getAnalysesOrBuilderList();
  /**
   * <code>repeated .debuff.AnalysisRecord analyses = 2;</code>
   */
  org.cyverse.de.protobufs.AnalysisRecordOrBuilder getAnalysesOrBuilder(
      int index);

  /**
   * <code>.debuff.ServiceError error = 7;</code>
   * @return Whether the error field is set.
   */
  boolean hasError();
  /**
   * <code>.debuff.ServiceError error = 7;</code>
   * @return The error.
   */
  org.cyverse.de.protobufs.ServiceError getError();
  /**
   * <code>.debuff.ServiceError error = 7;</code>
   */
  org.cyverse.de.protobufs.ServiceErrorOrBuilder getErrorOrBuilder();
}
