// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: analysis_requests.proto

package org.cyverse.de.protobufs;

/**
 * Protobuf type {@code AnalysisRecordList}
 */
public final class AnalysisRecordList extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:AnalysisRecordList)
    AnalysisRecordListOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AnalysisRecordList.newBuilder() to construct.
  private AnalysisRecordList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AnalysisRecordList() {
    analyses_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new AnalysisRecordList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private AnalysisRecordList(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            org.cyverse.de.protobufs.Header.Builder subBuilder = null;
            if (header_ != null) {
              subBuilder = header_.toBuilder();
            }
            header_ = input.readMessage(org.cyverse.de.protobufs.Header.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(header_);
              header_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              analyses_ = new java.util.ArrayList<org.cyverse.de.protobufs.AnalysisRecord>();
              mutable_bitField0_ |= 0x00000001;
            }
            analyses_.add(
                input.readMessage(org.cyverse.de.protobufs.AnalysisRecord.parser(), extensionRegistry));
            break;
          }
          case 58: {
            org.cyverse.de.protobufs.ServiceError.Builder subBuilder = null;
            if (error_ != null) {
              subBuilder = error_.toBuilder();
            }
            error_ = input.readMessage(org.cyverse.de.protobufs.ServiceError.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(error_);
              error_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        analyses_ = java.util.Collections.unmodifiableList(analyses_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.cyverse.de.protobufs.AnalysisRequestProtobufs.internal_static_AnalysisRecordList_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.cyverse.de.protobufs.AnalysisRequestProtobufs.internal_static_AnalysisRecordList_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.cyverse.de.protobufs.AnalysisRecordList.class, org.cyverse.de.protobufs.AnalysisRecordList.Builder.class);
  }

  public static final int HEADER_FIELD_NUMBER = 1;
  private org.cyverse.de.protobufs.Header header_;
  /**
   * <code>.Header header = 1;</code>
   * @return Whether the header field is set.
   */
  @java.lang.Override
  public boolean hasHeader() {
    return header_ != null;
  }
  /**
   * <code>.Header header = 1;</code>
   * @return The header.
   */
  @java.lang.Override
  public org.cyverse.de.protobufs.Header getHeader() {
    return header_ == null ? org.cyverse.de.protobufs.Header.getDefaultInstance() : header_;
  }
  /**
   * <code>.Header header = 1;</code>
   */
  @java.lang.Override
  public org.cyverse.de.protobufs.HeaderOrBuilder getHeaderOrBuilder() {
    return getHeader();
  }

  public static final int ANALYSES_FIELD_NUMBER = 2;
  private java.util.List<org.cyverse.de.protobufs.AnalysisRecord> analyses_;
  /**
   * <code>repeated .AnalysisRecord analyses = 2;</code>
   */
  @java.lang.Override
  public java.util.List<org.cyverse.de.protobufs.AnalysisRecord> getAnalysesList() {
    return analyses_;
  }
  /**
   * <code>repeated .AnalysisRecord analyses = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends org.cyverse.de.protobufs.AnalysisRecordOrBuilder> 
      getAnalysesOrBuilderList() {
    return analyses_;
  }
  /**
   * <code>repeated .AnalysisRecord analyses = 2;</code>
   */
  @java.lang.Override
  public int getAnalysesCount() {
    return analyses_.size();
  }
  /**
   * <code>repeated .AnalysisRecord analyses = 2;</code>
   */
  @java.lang.Override
  public org.cyverse.de.protobufs.AnalysisRecord getAnalyses(int index) {
    return analyses_.get(index);
  }
  /**
   * <code>repeated .AnalysisRecord analyses = 2;</code>
   */
  @java.lang.Override
  public org.cyverse.de.protobufs.AnalysisRecordOrBuilder getAnalysesOrBuilder(
      int index) {
    return analyses_.get(index);
  }

  public static final int ERROR_FIELD_NUMBER = 7;
  private org.cyverse.de.protobufs.ServiceError error_;
  /**
   * <code>.ServiceError error = 7;</code>
   * @return Whether the error field is set.
   */
  @java.lang.Override
  public boolean hasError() {
    return error_ != null;
  }
  /**
   * <code>.ServiceError error = 7;</code>
   * @return The error.
   */
  @java.lang.Override
  public org.cyverse.de.protobufs.ServiceError getError() {
    return error_ == null ? org.cyverse.de.protobufs.ServiceError.getDefaultInstance() : error_;
  }
  /**
   * <code>.ServiceError error = 7;</code>
   */
  @java.lang.Override
  public org.cyverse.de.protobufs.ServiceErrorOrBuilder getErrorOrBuilder() {
    return getError();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (header_ != null) {
      output.writeMessage(1, getHeader());
    }
    for (int i = 0; i < analyses_.size(); i++) {
      output.writeMessage(2, analyses_.get(i));
    }
    if (error_ != null) {
      output.writeMessage(7, getError());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (header_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getHeader());
    }
    for (int i = 0; i < analyses_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, analyses_.get(i));
    }
    if (error_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, getError());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.cyverse.de.protobufs.AnalysisRecordList)) {
      return super.equals(obj);
    }
    org.cyverse.de.protobufs.AnalysisRecordList other = (org.cyverse.de.protobufs.AnalysisRecordList) obj;

    if (hasHeader() != other.hasHeader()) return false;
    if (hasHeader()) {
      if (!getHeader()
          .equals(other.getHeader())) return false;
    }
    if (!getAnalysesList()
        .equals(other.getAnalysesList())) return false;
    if (hasError() != other.hasError()) return false;
    if (hasError()) {
      if (!getError()
          .equals(other.getError())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasHeader()) {
      hash = (37 * hash) + HEADER_FIELD_NUMBER;
      hash = (53 * hash) + getHeader().hashCode();
    }
    if (getAnalysesCount() > 0) {
      hash = (37 * hash) + ANALYSES_FIELD_NUMBER;
      hash = (53 * hash) + getAnalysesList().hashCode();
    }
    if (hasError()) {
      hash = (37 * hash) + ERROR_FIELD_NUMBER;
      hash = (53 * hash) + getError().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.cyverse.de.protobufs.AnalysisRecordList parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.cyverse.de.protobufs.AnalysisRecordList parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.cyverse.de.protobufs.AnalysisRecordList parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.cyverse.de.protobufs.AnalysisRecordList parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.cyverse.de.protobufs.AnalysisRecordList parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.cyverse.de.protobufs.AnalysisRecordList parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.cyverse.de.protobufs.AnalysisRecordList parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.cyverse.de.protobufs.AnalysisRecordList parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.cyverse.de.protobufs.AnalysisRecordList parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.cyverse.de.protobufs.AnalysisRecordList parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.cyverse.de.protobufs.AnalysisRecordList parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.cyverse.de.protobufs.AnalysisRecordList parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.cyverse.de.protobufs.AnalysisRecordList prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code AnalysisRecordList}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:AnalysisRecordList)
      org.cyverse.de.protobufs.AnalysisRecordListOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.cyverse.de.protobufs.AnalysisRequestProtobufs.internal_static_AnalysisRecordList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.cyverse.de.protobufs.AnalysisRequestProtobufs.internal_static_AnalysisRecordList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.cyverse.de.protobufs.AnalysisRecordList.class, org.cyverse.de.protobufs.AnalysisRecordList.Builder.class);
    }

    // Construct using org.cyverse.de.protobufs.AnalysisRecordList.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getAnalysesFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (headerBuilder_ == null) {
        header_ = null;
      } else {
        header_ = null;
        headerBuilder_ = null;
      }
      if (analysesBuilder_ == null) {
        analyses_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        analysesBuilder_.clear();
      }
      if (errorBuilder_ == null) {
        error_ = null;
      } else {
        error_ = null;
        errorBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.cyverse.de.protobufs.AnalysisRequestProtobufs.internal_static_AnalysisRecordList_descriptor;
    }

    @java.lang.Override
    public org.cyverse.de.protobufs.AnalysisRecordList getDefaultInstanceForType() {
      return org.cyverse.de.protobufs.AnalysisRecordList.getDefaultInstance();
    }

    @java.lang.Override
    public org.cyverse.de.protobufs.AnalysisRecordList build() {
      org.cyverse.de.protobufs.AnalysisRecordList result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.cyverse.de.protobufs.AnalysisRecordList buildPartial() {
      org.cyverse.de.protobufs.AnalysisRecordList result = new org.cyverse.de.protobufs.AnalysisRecordList(this);
      int from_bitField0_ = bitField0_;
      if (headerBuilder_ == null) {
        result.header_ = header_;
      } else {
        result.header_ = headerBuilder_.build();
      }
      if (analysesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          analyses_ = java.util.Collections.unmodifiableList(analyses_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.analyses_ = analyses_;
      } else {
        result.analyses_ = analysesBuilder_.build();
      }
      if (errorBuilder_ == null) {
        result.error_ = error_;
      } else {
        result.error_ = errorBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.cyverse.de.protobufs.AnalysisRecordList) {
        return mergeFrom((org.cyverse.de.protobufs.AnalysisRecordList)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.cyverse.de.protobufs.AnalysisRecordList other) {
      if (other == org.cyverse.de.protobufs.AnalysisRecordList.getDefaultInstance()) return this;
      if (other.hasHeader()) {
        mergeHeader(other.getHeader());
      }
      if (analysesBuilder_ == null) {
        if (!other.analyses_.isEmpty()) {
          if (analyses_.isEmpty()) {
            analyses_ = other.analyses_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureAnalysesIsMutable();
            analyses_.addAll(other.analyses_);
          }
          onChanged();
        }
      } else {
        if (!other.analyses_.isEmpty()) {
          if (analysesBuilder_.isEmpty()) {
            analysesBuilder_.dispose();
            analysesBuilder_ = null;
            analyses_ = other.analyses_;
            bitField0_ = (bitField0_ & ~0x00000001);
            analysesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getAnalysesFieldBuilder() : null;
          } else {
            analysesBuilder_.addAllMessages(other.analyses_);
          }
        }
      }
      if (other.hasError()) {
        mergeError(other.getError());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.cyverse.de.protobufs.AnalysisRecordList parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.cyverse.de.protobufs.AnalysisRecordList) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private org.cyverse.de.protobufs.Header header_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.cyverse.de.protobufs.Header, org.cyverse.de.protobufs.Header.Builder, org.cyverse.de.protobufs.HeaderOrBuilder> headerBuilder_;
    /**
     * <code>.Header header = 1;</code>
     * @return Whether the header field is set.
     */
    public boolean hasHeader() {
      return headerBuilder_ != null || header_ != null;
    }
    /**
     * <code>.Header header = 1;</code>
     * @return The header.
     */
    public org.cyverse.de.protobufs.Header getHeader() {
      if (headerBuilder_ == null) {
        return header_ == null ? org.cyverse.de.protobufs.Header.getDefaultInstance() : header_;
      } else {
        return headerBuilder_.getMessage();
      }
    }
    /**
     * <code>.Header header = 1;</code>
     */
    public Builder setHeader(org.cyverse.de.protobufs.Header value) {
      if (headerBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        header_ = value;
        onChanged();
      } else {
        headerBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.Header header = 1;</code>
     */
    public Builder setHeader(
        org.cyverse.de.protobufs.Header.Builder builderForValue) {
      if (headerBuilder_ == null) {
        header_ = builderForValue.build();
        onChanged();
      } else {
        headerBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.Header header = 1;</code>
     */
    public Builder mergeHeader(org.cyverse.de.protobufs.Header value) {
      if (headerBuilder_ == null) {
        if (header_ != null) {
          header_ =
            org.cyverse.de.protobufs.Header.newBuilder(header_).mergeFrom(value).buildPartial();
        } else {
          header_ = value;
        }
        onChanged();
      } else {
        headerBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.Header header = 1;</code>
     */
    public Builder clearHeader() {
      if (headerBuilder_ == null) {
        header_ = null;
        onChanged();
      } else {
        header_ = null;
        headerBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.Header header = 1;</code>
     */
    public org.cyverse.de.protobufs.Header.Builder getHeaderBuilder() {
      
      onChanged();
      return getHeaderFieldBuilder().getBuilder();
    }
    /**
     * <code>.Header header = 1;</code>
     */
    public org.cyverse.de.protobufs.HeaderOrBuilder getHeaderOrBuilder() {
      if (headerBuilder_ != null) {
        return headerBuilder_.getMessageOrBuilder();
      } else {
        return header_ == null ?
            org.cyverse.de.protobufs.Header.getDefaultInstance() : header_;
      }
    }
    /**
     * <code>.Header header = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.cyverse.de.protobufs.Header, org.cyverse.de.protobufs.Header.Builder, org.cyverse.de.protobufs.HeaderOrBuilder> 
        getHeaderFieldBuilder() {
      if (headerBuilder_ == null) {
        headerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.cyverse.de.protobufs.Header, org.cyverse.de.protobufs.Header.Builder, org.cyverse.de.protobufs.HeaderOrBuilder>(
                getHeader(),
                getParentForChildren(),
                isClean());
        header_ = null;
      }
      return headerBuilder_;
    }

    private java.util.List<org.cyverse.de.protobufs.AnalysisRecord> analyses_ =
      java.util.Collections.emptyList();
    private void ensureAnalysesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        analyses_ = new java.util.ArrayList<org.cyverse.de.protobufs.AnalysisRecord>(analyses_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.cyverse.de.protobufs.AnalysisRecord, org.cyverse.de.protobufs.AnalysisRecord.Builder, org.cyverse.de.protobufs.AnalysisRecordOrBuilder> analysesBuilder_;

    /**
     * <code>repeated .AnalysisRecord analyses = 2;</code>
     */
    public java.util.List<org.cyverse.de.protobufs.AnalysisRecord> getAnalysesList() {
      if (analysesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(analyses_);
      } else {
        return analysesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .AnalysisRecord analyses = 2;</code>
     */
    public int getAnalysesCount() {
      if (analysesBuilder_ == null) {
        return analyses_.size();
      } else {
        return analysesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .AnalysisRecord analyses = 2;</code>
     */
    public org.cyverse.de.protobufs.AnalysisRecord getAnalyses(int index) {
      if (analysesBuilder_ == null) {
        return analyses_.get(index);
      } else {
        return analysesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .AnalysisRecord analyses = 2;</code>
     */
    public Builder setAnalyses(
        int index, org.cyverse.de.protobufs.AnalysisRecord value) {
      if (analysesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAnalysesIsMutable();
        analyses_.set(index, value);
        onChanged();
      } else {
        analysesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .AnalysisRecord analyses = 2;</code>
     */
    public Builder setAnalyses(
        int index, org.cyverse.de.protobufs.AnalysisRecord.Builder builderForValue) {
      if (analysesBuilder_ == null) {
        ensureAnalysesIsMutable();
        analyses_.set(index, builderForValue.build());
        onChanged();
      } else {
        analysesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .AnalysisRecord analyses = 2;</code>
     */
    public Builder addAnalyses(org.cyverse.de.protobufs.AnalysisRecord value) {
      if (analysesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAnalysesIsMutable();
        analyses_.add(value);
        onChanged();
      } else {
        analysesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .AnalysisRecord analyses = 2;</code>
     */
    public Builder addAnalyses(
        int index, org.cyverse.de.protobufs.AnalysisRecord value) {
      if (analysesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAnalysesIsMutable();
        analyses_.add(index, value);
        onChanged();
      } else {
        analysesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .AnalysisRecord analyses = 2;</code>
     */
    public Builder addAnalyses(
        org.cyverse.de.protobufs.AnalysisRecord.Builder builderForValue) {
      if (analysesBuilder_ == null) {
        ensureAnalysesIsMutable();
        analyses_.add(builderForValue.build());
        onChanged();
      } else {
        analysesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .AnalysisRecord analyses = 2;</code>
     */
    public Builder addAnalyses(
        int index, org.cyverse.de.protobufs.AnalysisRecord.Builder builderForValue) {
      if (analysesBuilder_ == null) {
        ensureAnalysesIsMutable();
        analyses_.add(index, builderForValue.build());
        onChanged();
      } else {
        analysesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .AnalysisRecord analyses = 2;</code>
     */
    public Builder addAllAnalyses(
        java.lang.Iterable<? extends org.cyverse.de.protobufs.AnalysisRecord> values) {
      if (analysesBuilder_ == null) {
        ensureAnalysesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, analyses_);
        onChanged();
      } else {
        analysesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .AnalysisRecord analyses = 2;</code>
     */
    public Builder clearAnalyses() {
      if (analysesBuilder_ == null) {
        analyses_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        analysesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .AnalysisRecord analyses = 2;</code>
     */
    public Builder removeAnalyses(int index) {
      if (analysesBuilder_ == null) {
        ensureAnalysesIsMutable();
        analyses_.remove(index);
        onChanged();
      } else {
        analysesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .AnalysisRecord analyses = 2;</code>
     */
    public org.cyverse.de.protobufs.AnalysisRecord.Builder getAnalysesBuilder(
        int index) {
      return getAnalysesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .AnalysisRecord analyses = 2;</code>
     */
    public org.cyverse.de.protobufs.AnalysisRecordOrBuilder getAnalysesOrBuilder(
        int index) {
      if (analysesBuilder_ == null) {
        return analyses_.get(index);  } else {
        return analysesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .AnalysisRecord analyses = 2;</code>
     */
    public java.util.List<? extends org.cyverse.de.protobufs.AnalysisRecordOrBuilder> 
         getAnalysesOrBuilderList() {
      if (analysesBuilder_ != null) {
        return analysesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(analyses_);
      }
    }
    /**
     * <code>repeated .AnalysisRecord analyses = 2;</code>
     */
    public org.cyverse.de.protobufs.AnalysisRecord.Builder addAnalysesBuilder() {
      return getAnalysesFieldBuilder().addBuilder(
          org.cyverse.de.protobufs.AnalysisRecord.getDefaultInstance());
    }
    /**
     * <code>repeated .AnalysisRecord analyses = 2;</code>
     */
    public org.cyverse.de.protobufs.AnalysisRecord.Builder addAnalysesBuilder(
        int index) {
      return getAnalysesFieldBuilder().addBuilder(
          index, org.cyverse.de.protobufs.AnalysisRecord.getDefaultInstance());
    }
    /**
     * <code>repeated .AnalysisRecord analyses = 2;</code>
     */
    public java.util.List<org.cyverse.de.protobufs.AnalysisRecord.Builder> 
         getAnalysesBuilderList() {
      return getAnalysesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.cyverse.de.protobufs.AnalysisRecord, org.cyverse.de.protobufs.AnalysisRecord.Builder, org.cyverse.de.protobufs.AnalysisRecordOrBuilder> 
        getAnalysesFieldBuilder() {
      if (analysesBuilder_ == null) {
        analysesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            org.cyverse.de.protobufs.AnalysisRecord, org.cyverse.de.protobufs.AnalysisRecord.Builder, org.cyverse.de.protobufs.AnalysisRecordOrBuilder>(
                analyses_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        analyses_ = null;
      }
      return analysesBuilder_;
    }

    private org.cyverse.de.protobufs.ServiceError error_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.cyverse.de.protobufs.ServiceError, org.cyverse.de.protobufs.ServiceError.Builder, org.cyverse.de.protobufs.ServiceErrorOrBuilder> errorBuilder_;
    /**
     * <code>.ServiceError error = 7;</code>
     * @return Whether the error field is set.
     */
    public boolean hasError() {
      return errorBuilder_ != null || error_ != null;
    }
    /**
     * <code>.ServiceError error = 7;</code>
     * @return The error.
     */
    public org.cyverse.de.protobufs.ServiceError getError() {
      if (errorBuilder_ == null) {
        return error_ == null ? org.cyverse.de.protobufs.ServiceError.getDefaultInstance() : error_;
      } else {
        return errorBuilder_.getMessage();
      }
    }
    /**
     * <code>.ServiceError error = 7;</code>
     */
    public Builder setError(org.cyverse.de.protobufs.ServiceError value) {
      if (errorBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        error_ = value;
        onChanged();
      } else {
        errorBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.ServiceError error = 7;</code>
     */
    public Builder setError(
        org.cyverse.de.protobufs.ServiceError.Builder builderForValue) {
      if (errorBuilder_ == null) {
        error_ = builderForValue.build();
        onChanged();
      } else {
        errorBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.ServiceError error = 7;</code>
     */
    public Builder mergeError(org.cyverse.de.protobufs.ServiceError value) {
      if (errorBuilder_ == null) {
        if (error_ != null) {
          error_ =
            org.cyverse.de.protobufs.ServiceError.newBuilder(error_).mergeFrom(value).buildPartial();
        } else {
          error_ = value;
        }
        onChanged();
      } else {
        errorBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.ServiceError error = 7;</code>
     */
    public Builder clearError() {
      if (errorBuilder_ == null) {
        error_ = null;
        onChanged();
      } else {
        error_ = null;
        errorBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.ServiceError error = 7;</code>
     */
    public org.cyverse.de.protobufs.ServiceError.Builder getErrorBuilder() {
      
      onChanged();
      return getErrorFieldBuilder().getBuilder();
    }
    /**
     * <code>.ServiceError error = 7;</code>
     */
    public org.cyverse.de.protobufs.ServiceErrorOrBuilder getErrorOrBuilder() {
      if (errorBuilder_ != null) {
        return errorBuilder_.getMessageOrBuilder();
      } else {
        return error_ == null ?
            org.cyverse.de.protobufs.ServiceError.getDefaultInstance() : error_;
      }
    }
    /**
     * <code>.ServiceError error = 7;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.cyverse.de.protobufs.ServiceError, org.cyverse.de.protobufs.ServiceError.Builder, org.cyverse.de.protobufs.ServiceErrorOrBuilder> 
        getErrorFieldBuilder() {
      if (errorBuilder_ == null) {
        errorBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.cyverse.de.protobufs.ServiceError, org.cyverse.de.protobufs.ServiceError.Builder, org.cyverse.de.protobufs.ServiceErrorOrBuilder>(
                getError(),
                getParentForChildren(),
                isClean());
        error_ = null;
      }
      return errorBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:AnalysisRecordList)
  }

  // @@protoc_insertion_point(class_scope:AnalysisRecordList)
  private static final org.cyverse.de.protobufs.AnalysisRecordList DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.cyverse.de.protobufs.AnalysisRecordList();
  }

  public static org.cyverse.de.protobufs.AnalysisRecordList getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AnalysisRecordList>
      PARSER = new com.google.protobuf.AbstractParser<AnalysisRecordList>() {
    @java.lang.Override
    public AnalysisRecordList parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new AnalysisRecordList(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<AnalysisRecordList> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AnalysisRecordList> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.cyverse.de.protobufs.AnalysisRecordList getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

