// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: analysis_requests.proto

package org.cyverse.de.protobufs;

public interface AnalysisRecordResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AnalysisRecordResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Header header = 1;</code>
   * @return Whether the header field is set.
   */
  boolean hasHeader();
  /**
   * <code>.Header header = 1;</code>
   * @return The header.
   */
  org.cyverse.de.protobufs.Header getHeader();
  /**
   * <code>.Header header = 1;</code>
   */
  org.cyverse.de.protobufs.HeaderOrBuilder getHeaderOrBuilder();

  /**
   * <code>repeated .AnalysisRecord analyses = 2;</code>
   */
  java.util.List<org.cyverse.de.protobufs.AnalysisRecord> 
      getAnalysesList();
  /**
   * <code>repeated .AnalysisRecord analyses = 2;</code>
   */
  org.cyverse.de.protobufs.AnalysisRecord getAnalyses(int index);
  /**
   * <code>repeated .AnalysisRecord analyses = 2;</code>
   */
  int getAnalysesCount();
  /**
   * <code>repeated .AnalysisRecord analyses = 2;</code>
   */
  java.util.List<? extends org.cyverse.de.protobufs.AnalysisRecordOrBuilder> 
      getAnalysesOrBuilderList();
  /**
   * <code>repeated .AnalysisRecord analyses = 2;</code>
   */
  org.cyverse.de.protobufs.AnalysisRecordOrBuilder getAnalysesOrBuilder(
      int index);

  /**
   * <code>string timestamp = 3;</code>
   * @return The timestamp.
   */
  java.lang.String getTimestamp();
  /**
   * <code>string timestamp = 3;</code>
   * @return The bytes for timestamp.
   */
  com.google.protobuf.ByteString
      getTimestampBytes();

  /**
   * <code>int64 total = 4;</code>
   * @return The total.
   */
  long getTotal();

  /**
   * <code>repeated .AnalysisRecordResponse.StatusCountRecord status_count = 5 [json_name = "status-count"];</code>
   */
  java.util.List<org.cyverse.de.protobufs.AnalysisRecordResponse.StatusCountRecord> 
      getStatusCountList();
  /**
   * <code>repeated .AnalysisRecordResponse.StatusCountRecord status_count = 5 [json_name = "status-count"];</code>
   */
  org.cyverse.de.protobufs.AnalysisRecordResponse.StatusCountRecord getStatusCount(int index);
  /**
   * <code>repeated .AnalysisRecordResponse.StatusCountRecord status_count = 5 [json_name = "status-count"];</code>
   */
  int getStatusCountCount();
  /**
   * <code>repeated .AnalysisRecordResponse.StatusCountRecord status_count = 5 [json_name = "status-count"];</code>
   */
  java.util.List<? extends org.cyverse.de.protobufs.AnalysisRecordResponse.StatusCountRecordOrBuilder> 
      getStatusCountOrBuilderList();
  /**
   * <code>repeated .AnalysisRecordResponse.StatusCountRecord status_count = 5 [json_name = "status-count"];</code>
   */
  org.cyverse.de.protobufs.AnalysisRecordResponse.StatusCountRecordOrBuilder getStatusCountOrBuilder(
      int index);

  /**
   * <code>.ServiceError error = 6;</code>
   * @return Whether the error field is set.
   */
  boolean hasError();
  /**
   * <code>.ServiceError error = 6;</code>
   * @return The error.
   */
  org.cyverse.de.protobufs.ServiceError getError();
  /**
   * <code>.ServiceError error = 6;</code>
   */
  org.cyverse.de.protobufs.ServiceErrorOrBuilder getErrorOrBuilder();
}
