// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package org.cyverse.de.protobufs;

public interface LoginOrBuilder extends
    // @@protoc_insertion_point(interface_extends:user.Login)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string uuid = 1;</code>
   * @return The uuid.
   */
  java.lang.String getUuid();
  /**
   * <code>string uuid = 1;</code>
   * @return The bytes for uuid.
   */
  com.google.protobuf.ByteString
      getUuidBytes();

  /**
   * <code>string ip_address = 2;</code>
   * @return The ipAddress.
   */
  java.lang.String getIpAddress();
  /**
   * <code>string ip_address = 2;</code>
   * @return The bytes for ipAddress.
   */
  com.google.protobuf.ByteString
      getIpAddressBytes();

  /**
   * <code>string user_agent = 3;</code>
   * @return The userAgent.
   */
  java.lang.String getUserAgent();
  /**
   * <code>string user_agent = 3;</code>
   * @return The bytes for userAgent.
   */
  com.google.protobuf.ByteString
      getUserAgentBytes();

  /**
   * <code>.google.protobuf.Timestamp login_time = 4;</code>
   * @return Whether the loginTime field is set.
   */
  boolean hasLoginTime();
  /**
   * <code>.google.protobuf.Timestamp login_time = 4;</code>
   * @return The loginTime.
   */
  com.google.protobuf.Timestamp getLoginTime();
  /**
   * <code>.google.protobuf.Timestamp login_time = 4;</code>
   */
  com.google.protobuf.TimestampOrBuilder getLoginTimeOrBuilder();

  /**
   * <code>.google.protobuf.Timestamp logout_time = 5;</code>
   * @return Whether the logoutTime field is set.
   */
  boolean hasLogoutTime();
  /**
   * <code>.google.protobuf.Timestamp logout_time = 5;</code>
   * @return The logoutTime.
   */
  com.google.protobuf.Timestamp getLogoutTime();
  /**
   * <code>.google.protobuf.Timestamp logout_time = 5;</code>
   */
  com.google.protobuf.TimestampOrBuilder getLogoutTimeOrBuilder();
}
