// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: qms_plans.proto

package org.cyverse.de.protobufs;

/**
 * <pre>
 **
 * A response to a plan request. Contains a list of plans.
 * </pre>
 *
 * Protobuf type {@code PlanList}
 */
public final class PlanList extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:PlanList)
    PlanListOrBuilder {
private static final long serialVersionUID = 0L;
  // Use PlanList.newBuilder() to construct.
  private PlanList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PlanList() {
    plans_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new PlanList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.cyverse.de.protobufs.QMSPlansProtobufs.internal_static_PlanList_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.cyverse.de.protobufs.QMSPlansProtobufs.internal_static_PlanList_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.cyverse.de.protobufs.PlanList.class, org.cyverse.de.protobufs.PlanList.Builder.class);
  }

  public static final int HEADER_FIELD_NUMBER = 1;
  private org.cyverse.de.protobufs.Header header_;
  /**
   * <pre>
   * Contains telemetry data.
   * </pre>
   *
   * <code>.Header header = 1;</code>
   * @return Whether the header field is set.
   */
  @java.lang.Override
  public boolean hasHeader() {
    return header_ != null;
  }
  /**
   * <pre>
   * Contains telemetry data.
   * </pre>
   *
   * <code>.Header header = 1;</code>
   * @return The header.
   */
  @java.lang.Override
  public org.cyverse.de.protobufs.Header getHeader() {
    return header_ == null ? org.cyverse.de.protobufs.Header.getDefaultInstance() : header_;
  }
  /**
   * <pre>
   * Contains telemetry data.
   * </pre>
   *
   * <code>.Header header = 1;</code>
   */
  @java.lang.Override
  public org.cyverse.de.protobufs.HeaderOrBuilder getHeaderOrBuilder() {
    return header_ == null ? org.cyverse.de.protobufs.Header.getDefaultInstance() : header_;
  }

  public static final int ERROR_FIELD_NUMBER = 2;
  private org.cyverse.de.protobufs.ServiceError error_;
  /**
   * <pre>
   * Contains error data returned by the request handler.
   * </pre>
   *
   * <code>.ServiceError error = 2;</code>
   * @return Whether the error field is set.
   */
  @java.lang.Override
  public boolean hasError() {
    return error_ != null;
  }
  /**
   * <pre>
   * Contains error data returned by the request handler.
   * </pre>
   *
   * <code>.ServiceError error = 2;</code>
   * @return The error.
   */
  @java.lang.Override
  public org.cyverse.de.protobufs.ServiceError getError() {
    return error_ == null ? org.cyverse.de.protobufs.ServiceError.getDefaultInstance() : error_;
  }
  /**
   * <pre>
   * Contains error data returned by the request handler.
   * </pre>
   *
   * <code>.ServiceError error = 2;</code>
   */
  @java.lang.Override
  public org.cyverse.de.protobufs.ServiceErrorOrBuilder getErrorOrBuilder() {
    return error_ == null ? org.cyverse.de.protobufs.ServiceError.getDefaultInstance() : error_;
  }

  public static final int PLANS_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private java.util.List<org.cyverse.de.protobufs.Plan> plans_;
  /**
   * <pre>
   * A list of plans returned by the request handler.
   * </pre>
   *
   * <code>repeated .Plan plans = 3;</code>
   */
  @java.lang.Override
  public java.util.List<org.cyverse.de.protobufs.Plan> getPlansList() {
    return plans_;
  }
  /**
   * <pre>
   * A list of plans returned by the request handler.
   * </pre>
   *
   * <code>repeated .Plan plans = 3;</code>
   */
  @java.lang.Override
  public java.util.List<? extends org.cyverse.de.protobufs.PlanOrBuilder> 
      getPlansOrBuilderList() {
    return plans_;
  }
  /**
   * <pre>
   * A list of plans returned by the request handler.
   * </pre>
   *
   * <code>repeated .Plan plans = 3;</code>
   */
  @java.lang.Override
  public int getPlansCount() {
    return plans_.size();
  }
  /**
   * <pre>
   * A list of plans returned by the request handler.
   * </pre>
   *
   * <code>repeated .Plan plans = 3;</code>
   */
  @java.lang.Override
  public org.cyverse.de.protobufs.Plan getPlans(int index) {
    return plans_.get(index);
  }
  /**
   * <pre>
   * A list of plans returned by the request handler.
   * </pre>
   *
   * <code>repeated .Plan plans = 3;</code>
   */
  @java.lang.Override
  public org.cyverse.de.protobufs.PlanOrBuilder getPlansOrBuilder(
      int index) {
    return plans_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (header_ != null) {
      output.writeMessage(1, getHeader());
    }
    if (error_ != null) {
      output.writeMessage(2, getError());
    }
    for (int i = 0; i < plans_.size(); i++) {
      output.writeMessage(3, plans_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (header_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getHeader());
    }
    if (error_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getError());
    }
    for (int i = 0; i < plans_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, plans_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.cyverse.de.protobufs.PlanList)) {
      return super.equals(obj);
    }
    org.cyverse.de.protobufs.PlanList other = (org.cyverse.de.protobufs.PlanList) obj;

    if (hasHeader() != other.hasHeader()) return false;
    if (hasHeader()) {
      if (!getHeader()
          .equals(other.getHeader())) return false;
    }
    if (hasError() != other.hasError()) return false;
    if (hasError()) {
      if (!getError()
          .equals(other.getError())) return false;
    }
    if (!getPlansList()
        .equals(other.getPlansList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasHeader()) {
      hash = (37 * hash) + HEADER_FIELD_NUMBER;
      hash = (53 * hash) + getHeader().hashCode();
    }
    if (hasError()) {
      hash = (37 * hash) + ERROR_FIELD_NUMBER;
      hash = (53 * hash) + getError().hashCode();
    }
    if (getPlansCount() > 0) {
      hash = (37 * hash) + PLANS_FIELD_NUMBER;
      hash = (53 * hash) + getPlansList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.cyverse.de.protobufs.PlanList parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.cyverse.de.protobufs.PlanList parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.cyverse.de.protobufs.PlanList parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.cyverse.de.protobufs.PlanList parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.cyverse.de.protobufs.PlanList parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.cyverse.de.protobufs.PlanList parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.cyverse.de.protobufs.PlanList parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.cyverse.de.protobufs.PlanList parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.cyverse.de.protobufs.PlanList parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.cyverse.de.protobufs.PlanList parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.cyverse.de.protobufs.PlanList parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.cyverse.de.protobufs.PlanList parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.cyverse.de.protobufs.PlanList prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   **
   * A response to a plan request. Contains a list of plans.
   * </pre>
   *
   * Protobuf type {@code PlanList}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:PlanList)
      org.cyverse.de.protobufs.PlanListOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.cyverse.de.protobufs.QMSPlansProtobufs.internal_static_PlanList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.cyverse.de.protobufs.QMSPlansProtobufs.internal_static_PlanList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.cyverse.de.protobufs.PlanList.class, org.cyverse.de.protobufs.PlanList.Builder.class);
    }

    // Construct using org.cyverse.de.protobufs.PlanList.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      header_ = null;
      if (headerBuilder_ != null) {
        headerBuilder_.dispose();
        headerBuilder_ = null;
      }
      error_ = null;
      if (errorBuilder_ != null) {
        errorBuilder_.dispose();
        errorBuilder_ = null;
      }
      if (plansBuilder_ == null) {
        plans_ = java.util.Collections.emptyList();
      } else {
        plans_ = null;
        plansBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.cyverse.de.protobufs.QMSPlansProtobufs.internal_static_PlanList_descriptor;
    }

    @java.lang.Override
    public org.cyverse.de.protobufs.PlanList getDefaultInstanceForType() {
      return org.cyverse.de.protobufs.PlanList.getDefaultInstance();
    }

    @java.lang.Override
    public org.cyverse.de.protobufs.PlanList build() {
      org.cyverse.de.protobufs.PlanList result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.cyverse.de.protobufs.PlanList buildPartial() {
      org.cyverse.de.protobufs.PlanList result = new org.cyverse.de.protobufs.PlanList(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(org.cyverse.de.protobufs.PlanList result) {
      if (plansBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0)) {
          plans_ = java.util.Collections.unmodifiableList(plans_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.plans_ = plans_;
      } else {
        result.plans_ = plansBuilder_.build();
      }
    }

    private void buildPartial0(org.cyverse.de.protobufs.PlanList result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.header_ = headerBuilder_ == null
            ? header_
            : headerBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.error_ = errorBuilder_ == null
            ? error_
            : errorBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.cyverse.de.protobufs.PlanList) {
        return mergeFrom((org.cyverse.de.protobufs.PlanList)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.cyverse.de.protobufs.PlanList other) {
      if (other == org.cyverse.de.protobufs.PlanList.getDefaultInstance()) return this;
      if (other.hasHeader()) {
        mergeHeader(other.getHeader());
      }
      if (other.hasError()) {
        mergeError(other.getError());
      }
      if (plansBuilder_ == null) {
        if (!other.plans_.isEmpty()) {
          if (plans_.isEmpty()) {
            plans_ = other.plans_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensurePlansIsMutable();
            plans_.addAll(other.plans_);
          }
          onChanged();
        }
      } else {
        if (!other.plans_.isEmpty()) {
          if (plansBuilder_.isEmpty()) {
            plansBuilder_.dispose();
            plansBuilder_ = null;
            plans_ = other.plans_;
            bitField0_ = (bitField0_ & ~0x00000004);
            plansBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getPlansFieldBuilder() : null;
          } else {
            plansBuilder_.addAllMessages(other.plans_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getHeaderFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getErrorFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              org.cyverse.de.protobufs.Plan m =
                  input.readMessage(
                      org.cyverse.de.protobufs.Plan.parser(),
                      extensionRegistry);
              if (plansBuilder_ == null) {
                ensurePlansIsMutable();
                plans_.add(m);
              } else {
                plansBuilder_.addMessage(m);
              }
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private org.cyverse.de.protobufs.Header header_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.cyverse.de.protobufs.Header, org.cyverse.de.protobufs.Header.Builder, org.cyverse.de.protobufs.HeaderOrBuilder> headerBuilder_;
    /**
     * <pre>
     * Contains telemetry data.
     * </pre>
     *
     * <code>.Header header = 1;</code>
     * @return Whether the header field is set.
     */
    public boolean hasHeader() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * Contains telemetry data.
     * </pre>
     *
     * <code>.Header header = 1;</code>
     * @return The header.
     */
    public org.cyverse.de.protobufs.Header getHeader() {
      if (headerBuilder_ == null) {
        return header_ == null ? org.cyverse.de.protobufs.Header.getDefaultInstance() : header_;
      } else {
        return headerBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Contains telemetry data.
     * </pre>
     *
     * <code>.Header header = 1;</code>
     */
    public Builder setHeader(org.cyverse.de.protobufs.Header value) {
      if (headerBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        header_ = value;
      } else {
        headerBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Contains telemetry data.
     * </pre>
     *
     * <code>.Header header = 1;</code>
     */
    public Builder setHeader(
        org.cyverse.de.protobufs.Header.Builder builderForValue) {
      if (headerBuilder_ == null) {
        header_ = builderForValue.build();
      } else {
        headerBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Contains telemetry data.
     * </pre>
     *
     * <code>.Header header = 1;</code>
     */
    public Builder mergeHeader(org.cyverse.de.protobufs.Header value) {
      if (headerBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          header_ != null &&
          header_ != org.cyverse.de.protobufs.Header.getDefaultInstance()) {
          getHeaderBuilder().mergeFrom(value);
        } else {
          header_ = value;
        }
      } else {
        headerBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Contains telemetry data.
     * </pre>
     *
     * <code>.Header header = 1;</code>
     */
    public Builder clearHeader() {
      bitField0_ = (bitField0_ & ~0x00000001);
      header_ = null;
      if (headerBuilder_ != null) {
        headerBuilder_.dispose();
        headerBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Contains telemetry data.
     * </pre>
     *
     * <code>.Header header = 1;</code>
     */
    public org.cyverse.de.protobufs.Header.Builder getHeaderBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getHeaderFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Contains telemetry data.
     * </pre>
     *
     * <code>.Header header = 1;</code>
     */
    public org.cyverse.de.protobufs.HeaderOrBuilder getHeaderOrBuilder() {
      if (headerBuilder_ != null) {
        return headerBuilder_.getMessageOrBuilder();
      } else {
        return header_ == null ?
            org.cyverse.de.protobufs.Header.getDefaultInstance() : header_;
      }
    }
    /**
     * <pre>
     * Contains telemetry data.
     * </pre>
     *
     * <code>.Header header = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.cyverse.de.protobufs.Header, org.cyverse.de.protobufs.Header.Builder, org.cyverse.de.protobufs.HeaderOrBuilder> 
        getHeaderFieldBuilder() {
      if (headerBuilder_ == null) {
        headerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.cyverse.de.protobufs.Header, org.cyverse.de.protobufs.Header.Builder, org.cyverse.de.protobufs.HeaderOrBuilder>(
                getHeader(),
                getParentForChildren(),
                isClean());
        header_ = null;
      }
      return headerBuilder_;
    }

    private org.cyverse.de.protobufs.ServiceError error_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.cyverse.de.protobufs.ServiceError, org.cyverse.de.protobufs.ServiceError.Builder, org.cyverse.de.protobufs.ServiceErrorOrBuilder> errorBuilder_;
    /**
     * <pre>
     * Contains error data returned by the request handler.
     * </pre>
     *
     * <code>.ServiceError error = 2;</code>
     * @return Whether the error field is set.
     */
    public boolean hasError() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * Contains error data returned by the request handler.
     * </pre>
     *
     * <code>.ServiceError error = 2;</code>
     * @return The error.
     */
    public org.cyverse.de.protobufs.ServiceError getError() {
      if (errorBuilder_ == null) {
        return error_ == null ? org.cyverse.de.protobufs.ServiceError.getDefaultInstance() : error_;
      } else {
        return errorBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Contains error data returned by the request handler.
     * </pre>
     *
     * <code>.ServiceError error = 2;</code>
     */
    public Builder setError(org.cyverse.de.protobufs.ServiceError value) {
      if (errorBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        error_ = value;
      } else {
        errorBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Contains error data returned by the request handler.
     * </pre>
     *
     * <code>.ServiceError error = 2;</code>
     */
    public Builder setError(
        org.cyverse.de.protobufs.ServiceError.Builder builderForValue) {
      if (errorBuilder_ == null) {
        error_ = builderForValue.build();
      } else {
        errorBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Contains error data returned by the request handler.
     * </pre>
     *
     * <code>.ServiceError error = 2;</code>
     */
    public Builder mergeError(org.cyverse.de.protobufs.ServiceError value) {
      if (errorBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          error_ != null &&
          error_ != org.cyverse.de.protobufs.ServiceError.getDefaultInstance()) {
          getErrorBuilder().mergeFrom(value);
        } else {
          error_ = value;
        }
      } else {
        errorBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Contains error data returned by the request handler.
     * </pre>
     *
     * <code>.ServiceError error = 2;</code>
     */
    public Builder clearError() {
      bitField0_ = (bitField0_ & ~0x00000002);
      error_ = null;
      if (errorBuilder_ != null) {
        errorBuilder_.dispose();
        errorBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Contains error data returned by the request handler.
     * </pre>
     *
     * <code>.ServiceError error = 2;</code>
     */
    public org.cyverse.de.protobufs.ServiceError.Builder getErrorBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getErrorFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Contains error data returned by the request handler.
     * </pre>
     *
     * <code>.ServiceError error = 2;</code>
     */
    public org.cyverse.de.protobufs.ServiceErrorOrBuilder getErrorOrBuilder() {
      if (errorBuilder_ != null) {
        return errorBuilder_.getMessageOrBuilder();
      } else {
        return error_ == null ?
            org.cyverse.de.protobufs.ServiceError.getDefaultInstance() : error_;
      }
    }
    /**
     * <pre>
     * Contains error data returned by the request handler.
     * </pre>
     *
     * <code>.ServiceError error = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.cyverse.de.protobufs.ServiceError, org.cyverse.de.protobufs.ServiceError.Builder, org.cyverse.de.protobufs.ServiceErrorOrBuilder> 
        getErrorFieldBuilder() {
      if (errorBuilder_ == null) {
        errorBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.cyverse.de.protobufs.ServiceError, org.cyverse.de.protobufs.ServiceError.Builder, org.cyverse.de.protobufs.ServiceErrorOrBuilder>(
                getError(),
                getParentForChildren(),
                isClean());
        error_ = null;
      }
      return errorBuilder_;
    }

    private java.util.List<org.cyverse.de.protobufs.Plan> plans_ =
      java.util.Collections.emptyList();
    private void ensurePlansIsMutable() {
      if (!((bitField0_ & 0x00000004) != 0)) {
        plans_ = new java.util.ArrayList<org.cyverse.de.protobufs.Plan>(plans_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.cyverse.de.protobufs.Plan, org.cyverse.de.protobufs.Plan.Builder, org.cyverse.de.protobufs.PlanOrBuilder> plansBuilder_;

    /**
     * <pre>
     * A list of plans returned by the request handler.
     * </pre>
     *
     * <code>repeated .Plan plans = 3;</code>
     */
    public java.util.List<org.cyverse.de.protobufs.Plan> getPlansList() {
      if (plansBuilder_ == null) {
        return java.util.Collections.unmodifiableList(plans_);
      } else {
        return plansBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * A list of plans returned by the request handler.
     * </pre>
     *
     * <code>repeated .Plan plans = 3;</code>
     */
    public int getPlansCount() {
      if (plansBuilder_ == null) {
        return plans_.size();
      } else {
        return plansBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * A list of plans returned by the request handler.
     * </pre>
     *
     * <code>repeated .Plan plans = 3;</code>
     */
    public org.cyverse.de.protobufs.Plan getPlans(int index) {
      if (plansBuilder_ == null) {
        return plans_.get(index);
      } else {
        return plansBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * A list of plans returned by the request handler.
     * </pre>
     *
     * <code>repeated .Plan plans = 3;</code>
     */
    public Builder setPlans(
        int index, org.cyverse.de.protobufs.Plan value) {
      if (plansBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePlansIsMutable();
        plans_.set(index, value);
        onChanged();
      } else {
        plansBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * A list of plans returned by the request handler.
     * </pre>
     *
     * <code>repeated .Plan plans = 3;</code>
     */
    public Builder setPlans(
        int index, org.cyverse.de.protobufs.Plan.Builder builderForValue) {
      if (plansBuilder_ == null) {
        ensurePlansIsMutable();
        plans_.set(index, builderForValue.build());
        onChanged();
      } else {
        plansBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * A list of plans returned by the request handler.
     * </pre>
     *
     * <code>repeated .Plan plans = 3;</code>
     */
    public Builder addPlans(org.cyverse.de.protobufs.Plan value) {
      if (plansBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePlansIsMutable();
        plans_.add(value);
        onChanged();
      } else {
        plansBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * A list of plans returned by the request handler.
     * </pre>
     *
     * <code>repeated .Plan plans = 3;</code>
     */
    public Builder addPlans(
        int index, org.cyverse.de.protobufs.Plan value) {
      if (plansBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePlansIsMutable();
        plans_.add(index, value);
        onChanged();
      } else {
        plansBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * A list of plans returned by the request handler.
     * </pre>
     *
     * <code>repeated .Plan plans = 3;</code>
     */
    public Builder addPlans(
        org.cyverse.de.protobufs.Plan.Builder builderForValue) {
      if (plansBuilder_ == null) {
        ensurePlansIsMutable();
        plans_.add(builderForValue.build());
        onChanged();
      } else {
        plansBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * A list of plans returned by the request handler.
     * </pre>
     *
     * <code>repeated .Plan plans = 3;</code>
     */
    public Builder addPlans(
        int index, org.cyverse.de.protobufs.Plan.Builder builderForValue) {
      if (plansBuilder_ == null) {
        ensurePlansIsMutable();
        plans_.add(index, builderForValue.build());
        onChanged();
      } else {
        plansBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * A list of plans returned by the request handler.
     * </pre>
     *
     * <code>repeated .Plan plans = 3;</code>
     */
    public Builder addAllPlans(
        java.lang.Iterable<? extends org.cyverse.de.protobufs.Plan> values) {
      if (plansBuilder_ == null) {
        ensurePlansIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, plans_);
        onChanged();
      } else {
        plansBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * A list of plans returned by the request handler.
     * </pre>
     *
     * <code>repeated .Plan plans = 3;</code>
     */
    public Builder clearPlans() {
      if (plansBuilder_ == null) {
        plans_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        plansBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * A list of plans returned by the request handler.
     * </pre>
     *
     * <code>repeated .Plan plans = 3;</code>
     */
    public Builder removePlans(int index) {
      if (plansBuilder_ == null) {
        ensurePlansIsMutable();
        plans_.remove(index);
        onChanged();
      } else {
        plansBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * A list of plans returned by the request handler.
     * </pre>
     *
     * <code>repeated .Plan plans = 3;</code>
     */
    public org.cyverse.de.protobufs.Plan.Builder getPlansBuilder(
        int index) {
      return getPlansFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * A list of plans returned by the request handler.
     * </pre>
     *
     * <code>repeated .Plan plans = 3;</code>
     */
    public org.cyverse.de.protobufs.PlanOrBuilder getPlansOrBuilder(
        int index) {
      if (plansBuilder_ == null) {
        return plans_.get(index);  } else {
        return plansBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * A list of plans returned by the request handler.
     * </pre>
     *
     * <code>repeated .Plan plans = 3;</code>
     */
    public java.util.List<? extends org.cyverse.de.protobufs.PlanOrBuilder> 
         getPlansOrBuilderList() {
      if (plansBuilder_ != null) {
        return plansBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(plans_);
      }
    }
    /**
     * <pre>
     * A list of plans returned by the request handler.
     * </pre>
     *
     * <code>repeated .Plan plans = 3;</code>
     */
    public org.cyverse.de.protobufs.Plan.Builder addPlansBuilder() {
      return getPlansFieldBuilder().addBuilder(
          org.cyverse.de.protobufs.Plan.getDefaultInstance());
    }
    /**
     * <pre>
     * A list of plans returned by the request handler.
     * </pre>
     *
     * <code>repeated .Plan plans = 3;</code>
     */
    public org.cyverse.de.protobufs.Plan.Builder addPlansBuilder(
        int index) {
      return getPlansFieldBuilder().addBuilder(
          index, org.cyverse.de.protobufs.Plan.getDefaultInstance());
    }
    /**
     * <pre>
     * A list of plans returned by the request handler.
     * </pre>
     *
     * <code>repeated .Plan plans = 3;</code>
     */
    public java.util.List<org.cyverse.de.protobufs.Plan.Builder> 
         getPlansBuilderList() {
      return getPlansFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.cyverse.de.protobufs.Plan, org.cyverse.de.protobufs.Plan.Builder, org.cyverse.de.protobufs.PlanOrBuilder> 
        getPlansFieldBuilder() {
      if (plansBuilder_ == null) {
        plansBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            org.cyverse.de.protobufs.Plan, org.cyverse.de.protobufs.Plan.Builder, org.cyverse.de.protobufs.PlanOrBuilder>(
                plans_,
                ((bitField0_ & 0x00000004) != 0),
                getParentForChildren(),
                isClean());
        plans_ = null;
      }
      return plansBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:PlanList)
  }

  // @@protoc_insertion_point(class_scope:PlanList)
  private static final org.cyverse.de.protobufs.PlanList DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.cyverse.de.protobufs.PlanList();
  }

  public static org.cyverse.de.protobufs.PlanList getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PlanList>
      PARSER = new com.google.protobuf.AbstractParser<PlanList>() {
    @java.lang.Override
    public PlanList parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<PlanList> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PlanList> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.cyverse.de.protobufs.PlanList getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

