// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: qms_plans.proto

package org.cyverse.de.protobufs;

public interface PlanRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PlanRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Contains telemetry data.
   * </pre>
   *
   * <code>.Header header = 1;</code>
   * @return Whether the header field is set.
   */
  boolean hasHeader();
  /**
   * <pre>
   * Contains telemetry data.
   * </pre>
   *
   * <code>.Header header = 1;</code>
   * @return The header.
   */
  org.cyverse.de.protobufs.Header getHeader();
  /**
   * <pre>
   * Contains telemetry data.
   * </pre>
   *
   * <code>.Header header = 1;</code>
   */
  org.cyverse.de.protobufs.HeaderOrBuilder getHeaderOrBuilder();

  /**
   * <pre>
   * The unique identifier of the plan being requested.
   * </pre>
   *
   * <code>string plan_id = 2 [json_name = "plan_id"];</code>
   * @return The planId.
   */
  java.lang.String getPlanId();
  /**
   * <pre>
   * The unique identifier of the plan being requested.
   * </pre>
   *
   * <code>string plan_id = 2 [json_name = "plan_id"];</code>
   * @return The bytes for planId.
   */
  com.google.protobuf.ByteString
      getPlanIdBytes();
}
