// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: qms_plans.proto

package org.cyverse.de.protobufs;

/**
 * Protobuf type {@code QuotaDefault}
 */
public final class QuotaDefault extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:QuotaDefault)
    QuotaDefaultOrBuilder {
private static final long serialVersionUID = 0L;
  // Use QuotaDefault.newBuilder() to construct.
  private QuotaDefault(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private QuotaDefault() {
    uuid_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new QuotaDefault();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private QuotaDefault(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            uuid_ = s;
            break;
          }
          case 21: {

            quotaValue_ = input.readFloat();
            break;
          }
          case 26: {
            org.cyverse.de.protobufs.ResourceType.Builder subBuilder = null;
            if (resourceType_ != null) {
              subBuilder = resourceType_.toBuilder();
            }
            resourceType_ = input.readMessage(org.cyverse.de.protobufs.ResourceType.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(resourceType_);
              resourceType_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.cyverse.de.protobufs.QMSPlansProtobufs.internal_static_QuotaDefault_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.cyverse.de.protobufs.QMSPlansProtobufs.internal_static_QuotaDefault_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.cyverse.de.protobufs.QuotaDefault.class, org.cyverse.de.protobufs.QuotaDefault.Builder.class);
  }

  public static final int UUID_FIELD_NUMBER = 1;
  private volatile java.lang.Object uuid_;
  /**
   * <code>string uuid = 1;</code>
   * @return The uuid.
   */
  @java.lang.Override
  public java.lang.String getUuid() {
    java.lang.Object ref = uuid_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      uuid_ = s;
      return s;
    }
  }
  /**
   * <code>string uuid = 1;</code>
   * @return The bytes for uuid.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUuidBytes() {
    java.lang.Object ref = uuid_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      uuid_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int QUOTA_VALUE_FIELD_NUMBER = 2;
  private float quotaValue_;
  /**
   * <code>float quota_value = 2 [json_name = "quota_value"];</code>
   * @return The quotaValue.
   */
  @java.lang.Override
  public float getQuotaValue() {
    return quotaValue_;
  }

  public static final int RESOURCE_TYPE_FIELD_NUMBER = 3;
  private org.cyverse.de.protobufs.ResourceType resourceType_;
  /**
   * <code>.ResourceType resource_type = 3 [json_name = "resource_type"];</code>
   * @return Whether the resourceType field is set.
   */
  @java.lang.Override
  public boolean hasResourceType() {
    return resourceType_ != null;
  }
  /**
   * <code>.ResourceType resource_type = 3 [json_name = "resource_type"];</code>
   * @return The resourceType.
   */
  @java.lang.Override
  public org.cyverse.de.protobufs.ResourceType getResourceType() {
    return resourceType_ == null ? org.cyverse.de.protobufs.ResourceType.getDefaultInstance() : resourceType_;
  }
  /**
   * <code>.ResourceType resource_type = 3 [json_name = "resource_type"];</code>
   */
  @java.lang.Override
  public org.cyverse.de.protobufs.ResourceTypeOrBuilder getResourceTypeOrBuilder() {
    return getResourceType();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(uuid_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, uuid_);
    }
    if (java.lang.Float.floatToRawIntBits(quotaValue_) != 0) {
      output.writeFloat(2, quotaValue_);
    }
    if (resourceType_ != null) {
      output.writeMessage(3, getResourceType());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(uuid_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, uuid_);
    }
    if (java.lang.Float.floatToRawIntBits(quotaValue_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(2, quotaValue_);
    }
    if (resourceType_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getResourceType());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.cyverse.de.protobufs.QuotaDefault)) {
      return super.equals(obj);
    }
    org.cyverse.de.protobufs.QuotaDefault other = (org.cyverse.de.protobufs.QuotaDefault) obj;

    if (!getUuid()
        .equals(other.getUuid())) return false;
    if (java.lang.Float.floatToIntBits(getQuotaValue())
        != java.lang.Float.floatToIntBits(
            other.getQuotaValue())) return false;
    if (hasResourceType() != other.hasResourceType()) return false;
    if (hasResourceType()) {
      if (!getResourceType()
          .equals(other.getResourceType())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + UUID_FIELD_NUMBER;
    hash = (53 * hash) + getUuid().hashCode();
    hash = (37 * hash) + QUOTA_VALUE_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getQuotaValue());
    if (hasResourceType()) {
      hash = (37 * hash) + RESOURCE_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getResourceType().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.cyverse.de.protobufs.QuotaDefault parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.cyverse.de.protobufs.QuotaDefault parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.cyverse.de.protobufs.QuotaDefault parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.cyverse.de.protobufs.QuotaDefault parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.cyverse.de.protobufs.QuotaDefault parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.cyverse.de.protobufs.QuotaDefault parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.cyverse.de.protobufs.QuotaDefault parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.cyverse.de.protobufs.QuotaDefault parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.cyverse.de.protobufs.QuotaDefault parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.cyverse.de.protobufs.QuotaDefault parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.cyverse.de.protobufs.QuotaDefault parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.cyverse.de.protobufs.QuotaDefault parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.cyverse.de.protobufs.QuotaDefault prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code QuotaDefault}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:QuotaDefault)
      org.cyverse.de.protobufs.QuotaDefaultOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.cyverse.de.protobufs.QMSPlansProtobufs.internal_static_QuotaDefault_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.cyverse.de.protobufs.QMSPlansProtobufs.internal_static_QuotaDefault_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.cyverse.de.protobufs.QuotaDefault.class, org.cyverse.de.protobufs.QuotaDefault.Builder.class);
    }

    // Construct using org.cyverse.de.protobufs.QuotaDefault.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      uuid_ = "";

      quotaValue_ = 0F;

      if (resourceTypeBuilder_ == null) {
        resourceType_ = null;
      } else {
        resourceType_ = null;
        resourceTypeBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.cyverse.de.protobufs.QMSPlansProtobufs.internal_static_QuotaDefault_descriptor;
    }

    @java.lang.Override
    public org.cyverse.de.protobufs.QuotaDefault getDefaultInstanceForType() {
      return org.cyverse.de.protobufs.QuotaDefault.getDefaultInstance();
    }

    @java.lang.Override
    public org.cyverse.de.protobufs.QuotaDefault build() {
      org.cyverse.de.protobufs.QuotaDefault result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.cyverse.de.protobufs.QuotaDefault buildPartial() {
      org.cyverse.de.protobufs.QuotaDefault result = new org.cyverse.de.protobufs.QuotaDefault(this);
      result.uuid_ = uuid_;
      result.quotaValue_ = quotaValue_;
      if (resourceTypeBuilder_ == null) {
        result.resourceType_ = resourceType_;
      } else {
        result.resourceType_ = resourceTypeBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.cyverse.de.protobufs.QuotaDefault) {
        return mergeFrom((org.cyverse.de.protobufs.QuotaDefault)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.cyverse.de.protobufs.QuotaDefault other) {
      if (other == org.cyverse.de.protobufs.QuotaDefault.getDefaultInstance()) return this;
      if (!other.getUuid().isEmpty()) {
        uuid_ = other.uuid_;
        onChanged();
      }
      if (other.getQuotaValue() != 0F) {
        setQuotaValue(other.getQuotaValue());
      }
      if (other.hasResourceType()) {
        mergeResourceType(other.getResourceType());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.cyverse.de.protobufs.QuotaDefault parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.cyverse.de.protobufs.QuotaDefault) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object uuid_ = "";
    /**
     * <code>string uuid = 1;</code>
     * @return The uuid.
     */
    public java.lang.String getUuid() {
      java.lang.Object ref = uuid_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        uuid_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string uuid = 1;</code>
     * @return The bytes for uuid.
     */
    public com.google.protobuf.ByteString
        getUuidBytes() {
      java.lang.Object ref = uuid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uuid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string uuid = 1;</code>
     * @param value The uuid to set.
     * @return This builder for chaining.
     */
    public Builder setUuid(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      uuid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string uuid = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearUuid() {
      
      uuid_ = getDefaultInstance().getUuid();
      onChanged();
      return this;
    }
    /**
     * <code>string uuid = 1;</code>
     * @param value The bytes for uuid to set.
     * @return This builder for chaining.
     */
    public Builder setUuidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      uuid_ = value;
      onChanged();
      return this;
    }

    private float quotaValue_ ;
    /**
     * <code>float quota_value = 2 [json_name = "quota_value"];</code>
     * @return The quotaValue.
     */
    @java.lang.Override
    public float getQuotaValue() {
      return quotaValue_;
    }
    /**
     * <code>float quota_value = 2 [json_name = "quota_value"];</code>
     * @param value The quotaValue to set.
     * @return This builder for chaining.
     */
    public Builder setQuotaValue(float value) {
      
      quotaValue_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>float quota_value = 2 [json_name = "quota_value"];</code>
     * @return This builder for chaining.
     */
    public Builder clearQuotaValue() {
      
      quotaValue_ = 0F;
      onChanged();
      return this;
    }

    private org.cyverse.de.protobufs.ResourceType resourceType_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.cyverse.de.protobufs.ResourceType, org.cyverse.de.protobufs.ResourceType.Builder, org.cyverse.de.protobufs.ResourceTypeOrBuilder> resourceTypeBuilder_;
    /**
     * <code>.ResourceType resource_type = 3 [json_name = "resource_type"];</code>
     * @return Whether the resourceType field is set.
     */
    public boolean hasResourceType() {
      return resourceTypeBuilder_ != null || resourceType_ != null;
    }
    /**
     * <code>.ResourceType resource_type = 3 [json_name = "resource_type"];</code>
     * @return The resourceType.
     */
    public org.cyverse.de.protobufs.ResourceType getResourceType() {
      if (resourceTypeBuilder_ == null) {
        return resourceType_ == null ? org.cyverse.de.protobufs.ResourceType.getDefaultInstance() : resourceType_;
      } else {
        return resourceTypeBuilder_.getMessage();
      }
    }
    /**
     * <code>.ResourceType resource_type = 3 [json_name = "resource_type"];</code>
     */
    public Builder setResourceType(org.cyverse.de.protobufs.ResourceType value) {
      if (resourceTypeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        resourceType_ = value;
        onChanged();
      } else {
        resourceTypeBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.ResourceType resource_type = 3 [json_name = "resource_type"];</code>
     */
    public Builder setResourceType(
        org.cyverse.de.protobufs.ResourceType.Builder builderForValue) {
      if (resourceTypeBuilder_ == null) {
        resourceType_ = builderForValue.build();
        onChanged();
      } else {
        resourceTypeBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.ResourceType resource_type = 3 [json_name = "resource_type"];</code>
     */
    public Builder mergeResourceType(org.cyverse.de.protobufs.ResourceType value) {
      if (resourceTypeBuilder_ == null) {
        if (resourceType_ != null) {
          resourceType_ =
            org.cyverse.de.protobufs.ResourceType.newBuilder(resourceType_).mergeFrom(value).buildPartial();
        } else {
          resourceType_ = value;
        }
        onChanged();
      } else {
        resourceTypeBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.ResourceType resource_type = 3 [json_name = "resource_type"];</code>
     */
    public Builder clearResourceType() {
      if (resourceTypeBuilder_ == null) {
        resourceType_ = null;
        onChanged();
      } else {
        resourceType_ = null;
        resourceTypeBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.ResourceType resource_type = 3 [json_name = "resource_type"];</code>
     */
    public org.cyverse.de.protobufs.ResourceType.Builder getResourceTypeBuilder() {
      
      onChanged();
      return getResourceTypeFieldBuilder().getBuilder();
    }
    /**
     * <code>.ResourceType resource_type = 3 [json_name = "resource_type"];</code>
     */
    public org.cyverse.de.protobufs.ResourceTypeOrBuilder getResourceTypeOrBuilder() {
      if (resourceTypeBuilder_ != null) {
        return resourceTypeBuilder_.getMessageOrBuilder();
      } else {
        return resourceType_ == null ?
            org.cyverse.de.protobufs.ResourceType.getDefaultInstance() : resourceType_;
      }
    }
    /**
     * <code>.ResourceType resource_type = 3 [json_name = "resource_type"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.cyverse.de.protobufs.ResourceType, org.cyverse.de.protobufs.ResourceType.Builder, org.cyverse.de.protobufs.ResourceTypeOrBuilder> 
        getResourceTypeFieldBuilder() {
      if (resourceTypeBuilder_ == null) {
        resourceTypeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.cyverse.de.protobufs.ResourceType, org.cyverse.de.protobufs.ResourceType.Builder, org.cyverse.de.protobufs.ResourceTypeOrBuilder>(
                getResourceType(),
                getParentForChildren(),
                isClean());
        resourceType_ = null;
      }
      return resourceTypeBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:QuotaDefault)
  }

  // @@protoc_insertion_point(class_scope:QuotaDefault)
  private static final org.cyverse.de.protobufs.QuotaDefault DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.cyverse.de.protobufs.QuotaDefault();
  }

  public static org.cyverse.de.protobufs.QuotaDefault getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<QuotaDefault>
      PARSER = new com.google.protobuf.AbstractParser<QuotaDefault>() {
    @java.lang.Override
    public QuotaDefault parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new QuotaDefault(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<QuotaDefault> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<QuotaDefault> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.cyverse.de.protobufs.QuotaDefault getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

