// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: groups.proto

// Protobuf Java Version: 3.25.3
package org.cyverse.de.protobufs;

public interface ResourcesOutOrBuilder extends
    // @@protoc_insertion_point(interface_extends:groups.ResourcesOut)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The list of resources.
   * </pre>
   *
   * <code>repeated .groups.ResourceOut resources = 1;</code>
   */
  java.util.List<org.cyverse.de.protobufs.ResourceOut> 
      getResourcesList();
  /**
   * <pre>
   * The list of resources.
   * </pre>
   *
   * <code>repeated .groups.ResourceOut resources = 1;</code>
   */
  org.cyverse.de.protobufs.ResourceOut getResources(int index);
  /**
   * <pre>
   * The list of resources.
   * </pre>
   *
   * <code>repeated .groups.ResourceOut resources = 1;</code>
   */
  int getResourcesCount();
  /**
   * <pre>
   * The list of resources.
   * </pre>
   *
   * <code>repeated .groups.ResourceOut resources = 1;</code>
   */
  java.util.List<? extends org.cyverse.de.protobufs.ResourceOutOrBuilder> 
      getResourcesOrBuilderList();
  /**
   * <pre>
   * The list of resources.
   * </pre>
   *
   * <code>repeated .groups.ResourceOut resources = 1;</code>
   */
  org.cyverse.de.protobufs.ResourceOutOrBuilder getResourcesOrBuilder(
      int index);
}
