// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user_requests.proto

package org.cyverse.de.protobufs;

public interface SavedSearchesResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:user_requests.SavedSearchesResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .user.SavedSearchesWire searches = 1;</code>
   * @return Whether the searches field is set.
   */
  boolean hasSearches();
  /**
   * <code>optional .user.SavedSearchesWire searches = 1;</code>
   * @return The searches.
   */
  org.cyverse.de.protobufs.SavedSearchesWire getSearches();
  /**
   * <code>optional .user.SavedSearchesWire searches = 1;</code>
   */
  org.cyverse.de.protobufs.SavedSearchesWireOrBuilder getSearchesOrBuilder();

  /**
   * <code>optional .svcerror.Error error = 2;</code>
   * @return Whether the error field is set.
   */
  boolean hasError();
  /**
   * <code>optional .svcerror.Error error = 2;</code>
   * @return The error.
   */
  org.cyverse.de.protobufs.Error getError();
  /**
   * <code>optional .svcerror.Error error = 2;</code>
   */
  org.cyverse.de.protobufs.ErrorOrBuilder getErrorOrBuilder();
}
