// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: groups.proto
// Protobuf Java Version: 4.28.3

package org.cyverse.de.protobufs;

/**
 * <pre>
 * *
 * A list of incoming subjects.
 * </pre>
 *
 * Protobuf type {@code groups.SubjectsIn}
 */
public final class SubjectsIn extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:groups.SubjectsIn)
    SubjectsInOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 3,
      /* suffix= */ "",
      SubjectsIn.class.getName());
  }
  // Use SubjectsIn.newBuilder() to construct.
  private SubjectsIn(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private SubjectsIn() {
    subjects_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.cyverse.de.protobufs.GroupsProtobufs.internal_static_groups_SubjectsIn_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.cyverse.de.protobufs.GroupsProtobufs.internal_static_groups_SubjectsIn_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.cyverse.de.protobufs.SubjectsIn.class, org.cyverse.de.protobufs.SubjectsIn.Builder.class);
  }

  public static final int SUBJECTS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<org.cyverse.de.protobufs.SubjectIn> subjects_;
  /**
   * <pre>
   * The list of subjects.
   * </pre>
   *
   * <code>repeated .groups.SubjectIn subjects = 1;</code>
   */
  @java.lang.Override
  public java.util.List<org.cyverse.de.protobufs.SubjectIn> getSubjectsList() {
    return subjects_;
  }
  /**
   * <pre>
   * The list of subjects.
   * </pre>
   *
   * <code>repeated .groups.SubjectIn subjects = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends org.cyverse.de.protobufs.SubjectInOrBuilder> 
      getSubjectsOrBuilderList() {
    return subjects_;
  }
  /**
   * <pre>
   * The list of subjects.
   * </pre>
   *
   * <code>repeated .groups.SubjectIn subjects = 1;</code>
   */
  @java.lang.Override
  public int getSubjectsCount() {
    return subjects_.size();
  }
  /**
   * <pre>
   * The list of subjects.
   * </pre>
   *
   * <code>repeated .groups.SubjectIn subjects = 1;</code>
   */
  @java.lang.Override
  public org.cyverse.de.protobufs.SubjectIn getSubjects(int index) {
    return subjects_.get(index);
  }
  /**
   * <pre>
   * The list of subjects.
   * </pre>
   *
   * <code>repeated .groups.SubjectIn subjects = 1;</code>
   */
  @java.lang.Override
  public org.cyverse.de.protobufs.SubjectInOrBuilder getSubjectsOrBuilder(
      int index) {
    return subjects_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < subjects_.size(); i++) {
      output.writeMessage(1, subjects_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < subjects_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, subjects_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.cyverse.de.protobufs.SubjectsIn)) {
      return super.equals(obj);
    }
    org.cyverse.de.protobufs.SubjectsIn other = (org.cyverse.de.protobufs.SubjectsIn) obj;

    if (!getSubjectsList()
        .equals(other.getSubjectsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getSubjectsCount() > 0) {
      hash = (37 * hash) + SUBJECTS_FIELD_NUMBER;
      hash = (53 * hash) + getSubjectsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.cyverse.de.protobufs.SubjectsIn parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.cyverse.de.protobufs.SubjectsIn parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.cyverse.de.protobufs.SubjectsIn parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.cyverse.de.protobufs.SubjectsIn parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.cyverse.de.protobufs.SubjectsIn parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.cyverse.de.protobufs.SubjectsIn parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.cyverse.de.protobufs.SubjectsIn parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.cyverse.de.protobufs.SubjectsIn parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static org.cyverse.de.protobufs.SubjectsIn parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static org.cyverse.de.protobufs.SubjectsIn parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.cyverse.de.protobufs.SubjectsIn parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.cyverse.de.protobufs.SubjectsIn parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.cyverse.de.protobufs.SubjectsIn prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * *
   * A list of incoming subjects.
   * </pre>
   *
   * Protobuf type {@code groups.SubjectsIn}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:groups.SubjectsIn)
      org.cyverse.de.protobufs.SubjectsInOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.cyverse.de.protobufs.GroupsProtobufs.internal_static_groups_SubjectsIn_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.cyverse.de.protobufs.GroupsProtobufs.internal_static_groups_SubjectsIn_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.cyverse.de.protobufs.SubjectsIn.class, org.cyverse.de.protobufs.SubjectsIn.Builder.class);
    }

    // Construct using org.cyverse.de.protobufs.SubjectsIn.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (subjectsBuilder_ == null) {
        subjects_ = java.util.Collections.emptyList();
      } else {
        subjects_ = null;
        subjectsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.cyverse.de.protobufs.GroupsProtobufs.internal_static_groups_SubjectsIn_descriptor;
    }

    @java.lang.Override
    public org.cyverse.de.protobufs.SubjectsIn getDefaultInstanceForType() {
      return org.cyverse.de.protobufs.SubjectsIn.getDefaultInstance();
    }

    @java.lang.Override
    public org.cyverse.de.protobufs.SubjectsIn build() {
      org.cyverse.de.protobufs.SubjectsIn result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.cyverse.de.protobufs.SubjectsIn buildPartial() {
      org.cyverse.de.protobufs.SubjectsIn result = new org.cyverse.de.protobufs.SubjectsIn(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(org.cyverse.de.protobufs.SubjectsIn result) {
      if (subjectsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          subjects_ = java.util.Collections.unmodifiableList(subjects_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.subjects_ = subjects_;
      } else {
        result.subjects_ = subjectsBuilder_.build();
      }
    }

    private void buildPartial0(org.cyverse.de.protobufs.SubjectsIn result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.cyverse.de.protobufs.SubjectsIn) {
        return mergeFrom((org.cyverse.de.protobufs.SubjectsIn)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.cyverse.de.protobufs.SubjectsIn other) {
      if (other == org.cyverse.de.protobufs.SubjectsIn.getDefaultInstance()) return this;
      if (subjectsBuilder_ == null) {
        if (!other.subjects_.isEmpty()) {
          if (subjects_.isEmpty()) {
            subjects_ = other.subjects_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureSubjectsIsMutable();
            subjects_.addAll(other.subjects_);
          }
          onChanged();
        }
      } else {
        if (!other.subjects_.isEmpty()) {
          if (subjectsBuilder_.isEmpty()) {
            subjectsBuilder_.dispose();
            subjectsBuilder_ = null;
            subjects_ = other.subjects_;
            bitField0_ = (bitField0_ & ~0x00000001);
            subjectsBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getSubjectsFieldBuilder() : null;
          } else {
            subjectsBuilder_.addAllMessages(other.subjects_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              org.cyverse.de.protobufs.SubjectIn m =
                  input.readMessage(
                      org.cyverse.de.protobufs.SubjectIn.parser(),
                      extensionRegistry);
              if (subjectsBuilder_ == null) {
                ensureSubjectsIsMutable();
                subjects_.add(m);
              } else {
                subjectsBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<org.cyverse.de.protobufs.SubjectIn> subjects_ =
      java.util.Collections.emptyList();
    private void ensureSubjectsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        subjects_ = new java.util.ArrayList<org.cyverse.de.protobufs.SubjectIn>(subjects_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        org.cyverse.de.protobufs.SubjectIn, org.cyverse.de.protobufs.SubjectIn.Builder, org.cyverse.de.protobufs.SubjectInOrBuilder> subjectsBuilder_;

    /**
     * <pre>
     * The list of subjects.
     * </pre>
     *
     * <code>repeated .groups.SubjectIn subjects = 1;</code>
     */
    public java.util.List<org.cyverse.de.protobufs.SubjectIn> getSubjectsList() {
      if (subjectsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(subjects_);
      } else {
        return subjectsBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * The list of subjects.
     * </pre>
     *
     * <code>repeated .groups.SubjectIn subjects = 1;</code>
     */
    public int getSubjectsCount() {
      if (subjectsBuilder_ == null) {
        return subjects_.size();
      } else {
        return subjectsBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * The list of subjects.
     * </pre>
     *
     * <code>repeated .groups.SubjectIn subjects = 1;</code>
     */
    public org.cyverse.de.protobufs.SubjectIn getSubjects(int index) {
      if (subjectsBuilder_ == null) {
        return subjects_.get(index);
      } else {
        return subjectsBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * The list of subjects.
     * </pre>
     *
     * <code>repeated .groups.SubjectIn subjects = 1;</code>
     */
    public Builder setSubjects(
        int index, org.cyverse.de.protobufs.SubjectIn value) {
      if (subjectsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSubjectsIsMutable();
        subjects_.set(index, value);
        onChanged();
      } else {
        subjectsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * The list of subjects.
     * </pre>
     *
     * <code>repeated .groups.SubjectIn subjects = 1;</code>
     */
    public Builder setSubjects(
        int index, org.cyverse.de.protobufs.SubjectIn.Builder builderForValue) {
      if (subjectsBuilder_ == null) {
        ensureSubjectsIsMutable();
        subjects_.set(index, builderForValue.build());
        onChanged();
      } else {
        subjectsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * The list of subjects.
     * </pre>
     *
     * <code>repeated .groups.SubjectIn subjects = 1;</code>
     */
    public Builder addSubjects(org.cyverse.de.protobufs.SubjectIn value) {
      if (subjectsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSubjectsIsMutable();
        subjects_.add(value);
        onChanged();
      } else {
        subjectsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * The list of subjects.
     * </pre>
     *
     * <code>repeated .groups.SubjectIn subjects = 1;</code>
     */
    public Builder addSubjects(
        int index, org.cyverse.de.protobufs.SubjectIn value) {
      if (subjectsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSubjectsIsMutable();
        subjects_.add(index, value);
        onChanged();
      } else {
        subjectsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * The list of subjects.
     * </pre>
     *
     * <code>repeated .groups.SubjectIn subjects = 1;</code>
     */
    public Builder addSubjects(
        org.cyverse.de.protobufs.SubjectIn.Builder builderForValue) {
      if (subjectsBuilder_ == null) {
        ensureSubjectsIsMutable();
        subjects_.add(builderForValue.build());
        onChanged();
      } else {
        subjectsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * The list of subjects.
     * </pre>
     *
     * <code>repeated .groups.SubjectIn subjects = 1;</code>
     */
    public Builder addSubjects(
        int index, org.cyverse.de.protobufs.SubjectIn.Builder builderForValue) {
      if (subjectsBuilder_ == null) {
        ensureSubjectsIsMutable();
        subjects_.add(index, builderForValue.build());
        onChanged();
      } else {
        subjectsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * The list of subjects.
     * </pre>
     *
     * <code>repeated .groups.SubjectIn subjects = 1;</code>
     */
    public Builder addAllSubjects(
        java.lang.Iterable<? extends org.cyverse.de.protobufs.SubjectIn> values) {
      if (subjectsBuilder_ == null) {
        ensureSubjectsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, subjects_);
        onChanged();
      } else {
        subjectsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * The list of subjects.
     * </pre>
     *
     * <code>repeated .groups.SubjectIn subjects = 1;</code>
     */
    public Builder clearSubjects() {
      if (subjectsBuilder_ == null) {
        subjects_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        subjectsBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * The list of subjects.
     * </pre>
     *
     * <code>repeated .groups.SubjectIn subjects = 1;</code>
     */
    public Builder removeSubjects(int index) {
      if (subjectsBuilder_ == null) {
        ensureSubjectsIsMutable();
        subjects_.remove(index);
        onChanged();
      } else {
        subjectsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * The list of subjects.
     * </pre>
     *
     * <code>repeated .groups.SubjectIn subjects = 1;</code>
     */
    public org.cyverse.de.protobufs.SubjectIn.Builder getSubjectsBuilder(
        int index) {
      return getSubjectsFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * The list of subjects.
     * </pre>
     *
     * <code>repeated .groups.SubjectIn subjects = 1;</code>
     */
    public org.cyverse.de.protobufs.SubjectInOrBuilder getSubjectsOrBuilder(
        int index) {
      if (subjectsBuilder_ == null) {
        return subjects_.get(index);  } else {
        return subjectsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * The list of subjects.
     * </pre>
     *
     * <code>repeated .groups.SubjectIn subjects = 1;</code>
     */
    public java.util.List<? extends org.cyverse.de.protobufs.SubjectInOrBuilder> 
         getSubjectsOrBuilderList() {
      if (subjectsBuilder_ != null) {
        return subjectsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(subjects_);
      }
    }
    /**
     * <pre>
     * The list of subjects.
     * </pre>
     *
     * <code>repeated .groups.SubjectIn subjects = 1;</code>
     */
    public org.cyverse.de.protobufs.SubjectIn.Builder addSubjectsBuilder() {
      return getSubjectsFieldBuilder().addBuilder(
          org.cyverse.de.protobufs.SubjectIn.getDefaultInstance());
    }
    /**
     * <pre>
     * The list of subjects.
     * </pre>
     *
     * <code>repeated .groups.SubjectIn subjects = 1;</code>
     */
    public org.cyverse.de.protobufs.SubjectIn.Builder addSubjectsBuilder(
        int index) {
      return getSubjectsFieldBuilder().addBuilder(
          index, org.cyverse.de.protobufs.SubjectIn.getDefaultInstance());
    }
    /**
     * <pre>
     * The list of subjects.
     * </pre>
     *
     * <code>repeated .groups.SubjectIn subjects = 1;</code>
     */
    public java.util.List<org.cyverse.de.protobufs.SubjectIn.Builder> 
         getSubjectsBuilderList() {
      return getSubjectsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        org.cyverse.de.protobufs.SubjectIn, org.cyverse.de.protobufs.SubjectIn.Builder, org.cyverse.de.protobufs.SubjectInOrBuilder> 
        getSubjectsFieldBuilder() {
      if (subjectsBuilder_ == null) {
        subjectsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            org.cyverse.de.protobufs.SubjectIn, org.cyverse.de.protobufs.SubjectIn.Builder, org.cyverse.de.protobufs.SubjectInOrBuilder>(
                subjects_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        subjects_ = null;
      }
      return subjectsBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:groups.SubjectsIn)
  }

  // @@protoc_insertion_point(class_scope:groups.SubjectsIn)
  private static final org.cyverse.de.protobufs.SubjectsIn DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.cyverse.de.protobufs.SubjectsIn();
  }

  public static org.cyverse.de.protobufs.SubjectsIn getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SubjectsIn>
      PARSER = new com.google.protobuf.AbstractParser<SubjectsIn>() {
    @java.lang.Override
    public SubjectsIn parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<SubjectsIn> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SubjectsIn> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.cyverse.de.protobufs.SubjectsIn getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

