// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: groups.proto

package org.cyverse.de.protobufs;

public interface SubjectInOrBuilder extends
    // @@protoc_insertion_point(interface_extends:groups.SubjectIn)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The external subject identifier.
   * </pre>
   *
   * <code>string subject_id = 1 [json_name = "subject_id"];</code>
   * @return The subjectId.
   */
  java.lang.String getSubjectId();
  /**
   * <pre>
   * The external subject identifier.
   * </pre>
   *
   * <code>string subject_id = 1 [json_name = "subject_id"];</code>
   * @return The bytes for subjectId.
   */
  com.google.protobuf.ByteString
      getSubjectIdBytes();

  /**
   * <pre>
   * The subject type.
   * </pre>
   *
   * <code>string subject_type = 2 [json_name = "subject_type"];</code>
   * @return The subjectType.
   */
  java.lang.String getSubjectType();
  /**
   * <pre>
   * The subject type.
   * </pre>
   *
   * <code>string subject_type = 2 [json_name = "subject_type"];</code>
   * @return The bytes for subjectType.
   */
  com.google.protobuf.ByteString
      getSubjectTypeBytes();
}
