// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: qms_addons.proto

package org.cyverse.de.protobufs;

/**
 * <pre>
 **
 * SubscriptionAddon is an add-on that has been applied to a subscription. It 
 * contains fields that can override the the default_amount and default_paid 
 * fields in the subscription.
 * </pre>
 *
 * Protobuf type {@code qms.SubscriptionAddon}
 */
public final class SubscriptionAddon extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:qms.SubscriptionAddon)
    SubscriptionAddonOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SubscriptionAddon.newBuilder() to construct.
  private SubscriptionAddon(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SubscriptionAddon() {
    uuid_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new SubscriptionAddon();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.cyverse.de.protobufs.QMSAddonProtobufs.internal_static_qms_SubscriptionAddon_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.cyverse.de.protobufs.QMSAddonProtobufs.internal_static_qms_SubscriptionAddon_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.cyverse.de.protobufs.SubscriptionAddon.class, org.cyverse.de.protobufs.SubscriptionAddon.Builder.class);
  }

  public static final int UUID_FIELD_NUMBER = 1;
  private volatile java.lang.Object uuid_;
  /**
   * <pre>
   * The unique identifier for the add-on
   * </pre>
   *
   * <code>string uuid = 1;</code>
   * @return The uuid.
   */
  @java.lang.Override
  public java.lang.String getUuid() {
    java.lang.Object ref = uuid_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      uuid_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The unique identifier for the add-on
   * </pre>
   *
   * <code>string uuid = 1;</code>
   * @return The bytes for uuid.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUuidBytes() {
    java.lang.Object ref = uuid_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      uuid_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ADDON_FIELD_NUMBER = 2;
  private org.cyverse.de.protobufs.Addon addon_;
  /**
   * <pre>
   * The add-on used with the subscription. May only contain the add-on's 
   * UUID in some circumstances.
   * </pre>
   *
   * <code>.qms.Addon addon = 2;</code>
   * @return Whether the addon field is set.
   */
  @java.lang.Override
  public boolean hasAddon() {
    return addon_ != null;
  }
  /**
   * <pre>
   * The add-on used with the subscription. May only contain the add-on's 
   * UUID in some circumstances.
   * </pre>
   *
   * <code>.qms.Addon addon = 2;</code>
   * @return The addon.
   */
  @java.lang.Override
  public org.cyverse.de.protobufs.Addon getAddon() {
    return addon_ == null ? org.cyverse.de.protobufs.Addon.getDefaultInstance() : addon_;
  }
  /**
   * <pre>
   * The add-on used with the subscription. May only contain the add-on's 
   * UUID in some circumstances.
   * </pre>
   *
   * <code>.qms.Addon addon = 2;</code>
   */
  @java.lang.Override
  public org.cyverse.de.protobufs.AddonOrBuilder getAddonOrBuilder() {
    return getAddon();
  }

  public static final int SUBSCRIPTION_FIELD_NUMBER = 3;
  private org.cyverse.de.protobufs.Subscription subscription_;
  /**
   * <pre>
   * The subscription the add-on was applied to. May only contain the add-on's
   * UUID in some circumstances.
   * </pre>
   *
   * <code>.qms.Subscription subscription = 3;</code>
   * @return Whether the subscription field is set.
   */
  @java.lang.Override
  public boolean hasSubscription() {
    return subscription_ != null;
  }
  /**
   * <pre>
   * The subscription the add-on was applied to. May only contain the add-on's
   * UUID in some circumstances.
   * </pre>
   *
   * <code>.qms.Subscription subscription = 3;</code>
   * @return The subscription.
   */
  @java.lang.Override
  public org.cyverse.de.protobufs.Subscription getSubscription() {
    return subscription_ == null ? org.cyverse.de.protobufs.Subscription.getDefaultInstance() : subscription_;
  }
  /**
   * <pre>
   * The subscription the add-on was applied to. May only contain the add-on's
   * UUID in some circumstances.
   * </pre>
   *
   * <code>.qms.Subscription subscription = 3;</code>
   */
  @java.lang.Override
  public org.cyverse.de.protobufs.SubscriptionOrBuilder getSubscriptionOrBuilder() {
    return getSubscription();
  }

  public static final int AMOUNT_FIELD_NUMBER = 4;
  private double amount_;
  /**
   * <pre>
   * The amount of the resource applied by the add-on. This should default to
   * the amount contained in the add-on definition, but can be overridden, 
   * which is why it's a separate field here.
   * </pre>
   *
   * <code>double amount = 4;</code>
   * @return The amount.
   */
  @java.lang.Override
  public double getAmount() {
    return amount_;
  }

  public static final int PAID_FIELD_NUMBER = 5;
  private boolean paid_;
  /**
   * <pre>
   * Whether the subscription add-on costs money. This should default to the 
   * same paid value contained in the add-on definition, but can be overridden,
   * which is whay it's a separate field here.
   * </pre>
   *
   * <code>bool paid = 5;</code>
   * @return The paid.
   */
  @java.lang.Override
  public boolean getPaid() {
    return paid_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(uuid_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, uuid_);
    }
    if (addon_ != null) {
      output.writeMessage(2, getAddon());
    }
    if (subscription_ != null) {
      output.writeMessage(3, getSubscription());
    }
    if (java.lang.Double.doubleToRawLongBits(amount_) != 0) {
      output.writeDouble(4, amount_);
    }
    if (paid_ != false) {
      output.writeBool(5, paid_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(uuid_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, uuid_);
    }
    if (addon_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getAddon());
    }
    if (subscription_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getSubscription());
    }
    if (java.lang.Double.doubleToRawLongBits(amount_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(4, amount_);
    }
    if (paid_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(5, paid_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.cyverse.de.protobufs.SubscriptionAddon)) {
      return super.equals(obj);
    }
    org.cyverse.de.protobufs.SubscriptionAddon other = (org.cyverse.de.protobufs.SubscriptionAddon) obj;

    if (!getUuid()
        .equals(other.getUuid())) return false;
    if (hasAddon() != other.hasAddon()) return false;
    if (hasAddon()) {
      if (!getAddon()
          .equals(other.getAddon())) return false;
    }
    if (hasSubscription() != other.hasSubscription()) return false;
    if (hasSubscription()) {
      if (!getSubscription()
          .equals(other.getSubscription())) return false;
    }
    if (java.lang.Double.doubleToLongBits(getAmount())
        != java.lang.Double.doubleToLongBits(
            other.getAmount())) return false;
    if (getPaid()
        != other.getPaid()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + UUID_FIELD_NUMBER;
    hash = (53 * hash) + getUuid().hashCode();
    if (hasAddon()) {
      hash = (37 * hash) + ADDON_FIELD_NUMBER;
      hash = (53 * hash) + getAddon().hashCode();
    }
    if (hasSubscription()) {
      hash = (37 * hash) + SUBSCRIPTION_FIELD_NUMBER;
      hash = (53 * hash) + getSubscription().hashCode();
    }
    hash = (37 * hash) + AMOUNT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getAmount()));
    hash = (37 * hash) + PAID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getPaid());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.cyverse.de.protobufs.SubscriptionAddon parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.cyverse.de.protobufs.SubscriptionAddon parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.cyverse.de.protobufs.SubscriptionAddon parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.cyverse.de.protobufs.SubscriptionAddon parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.cyverse.de.protobufs.SubscriptionAddon parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.cyverse.de.protobufs.SubscriptionAddon parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.cyverse.de.protobufs.SubscriptionAddon parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.cyverse.de.protobufs.SubscriptionAddon parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.cyverse.de.protobufs.SubscriptionAddon parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.cyverse.de.protobufs.SubscriptionAddon parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.cyverse.de.protobufs.SubscriptionAddon parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.cyverse.de.protobufs.SubscriptionAddon parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.cyverse.de.protobufs.SubscriptionAddon prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   **
   * SubscriptionAddon is an add-on that has been applied to a subscription. It 
   * contains fields that can override the the default_amount and default_paid 
   * fields in the subscription.
   * </pre>
   *
   * Protobuf type {@code qms.SubscriptionAddon}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:qms.SubscriptionAddon)
      org.cyverse.de.protobufs.SubscriptionAddonOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.cyverse.de.protobufs.QMSAddonProtobufs.internal_static_qms_SubscriptionAddon_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.cyverse.de.protobufs.QMSAddonProtobufs.internal_static_qms_SubscriptionAddon_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.cyverse.de.protobufs.SubscriptionAddon.class, org.cyverse.de.protobufs.SubscriptionAddon.Builder.class);
    }

    // Construct using org.cyverse.de.protobufs.SubscriptionAddon.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      uuid_ = "";

      if (addonBuilder_ == null) {
        addon_ = null;
      } else {
        addon_ = null;
        addonBuilder_ = null;
      }
      if (subscriptionBuilder_ == null) {
        subscription_ = null;
      } else {
        subscription_ = null;
        subscriptionBuilder_ = null;
      }
      amount_ = 0D;

      paid_ = false;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.cyverse.de.protobufs.QMSAddonProtobufs.internal_static_qms_SubscriptionAddon_descriptor;
    }

    @java.lang.Override
    public org.cyverse.de.protobufs.SubscriptionAddon getDefaultInstanceForType() {
      return org.cyverse.de.protobufs.SubscriptionAddon.getDefaultInstance();
    }

    @java.lang.Override
    public org.cyverse.de.protobufs.SubscriptionAddon build() {
      org.cyverse.de.protobufs.SubscriptionAddon result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.cyverse.de.protobufs.SubscriptionAddon buildPartial() {
      org.cyverse.de.protobufs.SubscriptionAddon result = new org.cyverse.de.protobufs.SubscriptionAddon(this);
      result.uuid_ = uuid_;
      if (addonBuilder_ == null) {
        result.addon_ = addon_;
      } else {
        result.addon_ = addonBuilder_.build();
      }
      if (subscriptionBuilder_ == null) {
        result.subscription_ = subscription_;
      } else {
        result.subscription_ = subscriptionBuilder_.build();
      }
      result.amount_ = amount_;
      result.paid_ = paid_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.cyverse.de.protobufs.SubscriptionAddon) {
        return mergeFrom((org.cyverse.de.protobufs.SubscriptionAddon)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.cyverse.de.protobufs.SubscriptionAddon other) {
      if (other == org.cyverse.de.protobufs.SubscriptionAddon.getDefaultInstance()) return this;
      if (!other.getUuid().isEmpty()) {
        uuid_ = other.uuid_;
        onChanged();
      }
      if (other.hasAddon()) {
        mergeAddon(other.getAddon());
      }
      if (other.hasSubscription()) {
        mergeSubscription(other.getSubscription());
      }
      if (other.getAmount() != 0D) {
        setAmount(other.getAmount());
      }
      if (other.getPaid() != false) {
        setPaid(other.getPaid());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              uuid_ = input.readStringRequireUtf8();

              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getAddonFieldBuilder().getBuilder(),
                  extensionRegistry);

              break;
            } // case 18
            case 26: {
              input.readMessage(
                  getSubscriptionFieldBuilder().getBuilder(),
                  extensionRegistry);

              break;
            } // case 26
            case 33: {
              amount_ = input.readDouble();

              break;
            } // case 33
            case 40: {
              paid_ = input.readBool();

              break;
            } // case 40
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }

    private java.lang.Object uuid_ = "";
    /**
     * <pre>
     * The unique identifier for the add-on
     * </pre>
     *
     * <code>string uuid = 1;</code>
     * @return The uuid.
     */
    public java.lang.String getUuid() {
      java.lang.Object ref = uuid_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        uuid_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The unique identifier for the add-on
     * </pre>
     *
     * <code>string uuid = 1;</code>
     * @return The bytes for uuid.
     */
    public com.google.protobuf.ByteString
        getUuidBytes() {
      java.lang.Object ref = uuid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uuid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The unique identifier for the add-on
     * </pre>
     *
     * <code>string uuid = 1;</code>
     * @param value The uuid to set.
     * @return This builder for chaining.
     */
    public Builder setUuid(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      uuid_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The unique identifier for the add-on
     * </pre>
     *
     * <code>string uuid = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearUuid() {
      
      uuid_ = getDefaultInstance().getUuid();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The unique identifier for the add-on
     * </pre>
     *
     * <code>string uuid = 1;</code>
     * @param value The bytes for uuid to set.
     * @return This builder for chaining.
     */
    public Builder setUuidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      uuid_ = value;
      onChanged();
      return this;
    }

    private org.cyverse.de.protobufs.Addon addon_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.cyverse.de.protobufs.Addon, org.cyverse.de.protobufs.Addon.Builder, org.cyverse.de.protobufs.AddonOrBuilder> addonBuilder_;
    /**
     * <pre>
     * The add-on used with the subscription. May only contain the add-on's 
     * UUID in some circumstances.
     * </pre>
     *
     * <code>.qms.Addon addon = 2;</code>
     * @return Whether the addon field is set.
     */
    public boolean hasAddon() {
      return addonBuilder_ != null || addon_ != null;
    }
    /**
     * <pre>
     * The add-on used with the subscription. May only contain the add-on's 
     * UUID in some circumstances.
     * </pre>
     *
     * <code>.qms.Addon addon = 2;</code>
     * @return The addon.
     */
    public org.cyverse.de.protobufs.Addon getAddon() {
      if (addonBuilder_ == null) {
        return addon_ == null ? org.cyverse.de.protobufs.Addon.getDefaultInstance() : addon_;
      } else {
        return addonBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * The add-on used with the subscription. May only contain the add-on's 
     * UUID in some circumstances.
     * </pre>
     *
     * <code>.qms.Addon addon = 2;</code>
     */
    public Builder setAddon(org.cyverse.de.protobufs.Addon value) {
      if (addonBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        addon_ = value;
        onChanged();
      } else {
        addonBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * The add-on used with the subscription. May only contain the add-on's 
     * UUID in some circumstances.
     * </pre>
     *
     * <code>.qms.Addon addon = 2;</code>
     */
    public Builder setAddon(
        org.cyverse.de.protobufs.Addon.Builder builderForValue) {
      if (addonBuilder_ == null) {
        addon_ = builderForValue.build();
        onChanged();
      } else {
        addonBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * The add-on used with the subscription. May only contain the add-on's 
     * UUID in some circumstances.
     * </pre>
     *
     * <code>.qms.Addon addon = 2;</code>
     */
    public Builder mergeAddon(org.cyverse.de.protobufs.Addon value) {
      if (addonBuilder_ == null) {
        if (addon_ != null) {
          addon_ =
            org.cyverse.de.protobufs.Addon.newBuilder(addon_).mergeFrom(value).buildPartial();
        } else {
          addon_ = value;
        }
        onChanged();
      } else {
        addonBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * The add-on used with the subscription. May only contain the add-on's 
     * UUID in some circumstances.
     * </pre>
     *
     * <code>.qms.Addon addon = 2;</code>
     */
    public Builder clearAddon() {
      if (addonBuilder_ == null) {
        addon_ = null;
        onChanged();
      } else {
        addon_ = null;
        addonBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * The add-on used with the subscription. May only contain the add-on's 
     * UUID in some circumstances.
     * </pre>
     *
     * <code>.qms.Addon addon = 2;</code>
     */
    public org.cyverse.de.protobufs.Addon.Builder getAddonBuilder() {
      
      onChanged();
      return getAddonFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * The add-on used with the subscription. May only contain the add-on's 
     * UUID in some circumstances.
     * </pre>
     *
     * <code>.qms.Addon addon = 2;</code>
     */
    public org.cyverse.de.protobufs.AddonOrBuilder getAddonOrBuilder() {
      if (addonBuilder_ != null) {
        return addonBuilder_.getMessageOrBuilder();
      } else {
        return addon_ == null ?
            org.cyverse.de.protobufs.Addon.getDefaultInstance() : addon_;
      }
    }
    /**
     * <pre>
     * The add-on used with the subscription. May only contain the add-on's 
     * UUID in some circumstances.
     * </pre>
     *
     * <code>.qms.Addon addon = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.cyverse.de.protobufs.Addon, org.cyverse.de.protobufs.Addon.Builder, org.cyverse.de.protobufs.AddonOrBuilder> 
        getAddonFieldBuilder() {
      if (addonBuilder_ == null) {
        addonBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.cyverse.de.protobufs.Addon, org.cyverse.de.protobufs.Addon.Builder, org.cyverse.de.protobufs.AddonOrBuilder>(
                getAddon(),
                getParentForChildren(),
                isClean());
        addon_ = null;
      }
      return addonBuilder_;
    }

    private org.cyverse.de.protobufs.Subscription subscription_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.cyverse.de.protobufs.Subscription, org.cyverse.de.protobufs.Subscription.Builder, org.cyverse.de.protobufs.SubscriptionOrBuilder> subscriptionBuilder_;
    /**
     * <pre>
     * The subscription the add-on was applied to. May only contain the add-on's
     * UUID in some circumstances.
     * </pre>
     *
     * <code>.qms.Subscription subscription = 3;</code>
     * @return Whether the subscription field is set.
     */
    public boolean hasSubscription() {
      return subscriptionBuilder_ != null || subscription_ != null;
    }
    /**
     * <pre>
     * The subscription the add-on was applied to. May only contain the add-on's
     * UUID in some circumstances.
     * </pre>
     *
     * <code>.qms.Subscription subscription = 3;</code>
     * @return The subscription.
     */
    public org.cyverse.de.protobufs.Subscription getSubscription() {
      if (subscriptionBuilder_ == null) {
        return subscription_ == null ? org.cyverse.de.protobufs.Subscription.getDefaultInstance() : subscription_;
      } else {
        return subscriptionBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * The subscription the add-on was applied to. May only contain the add-on's
     * UUID in some circumstances.
     * </pre>
     *
     * <code>.qms.Subscription subscription = 3;</code>
     */
    public Builder setSubscription(org.cyverse.de.protobufs.Subscription value) {
      if (subscriptionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        subscription_ = value;
        onChanged();
      } else {
        subscriptionBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * The subscription the add-on was applied to. May only contain the add-on's
     * UUID in some circumstances.
     * </pre>
     *
     * <code>.qms.Subscription subscription = 3;</code>
     */
    public Builder setSubscription(
        org.cyverse.de.protobufs.Subscription.Builder builderForValue) {
      if (subscriptionBuilder_ == null) {
        subscription_ = builderForValue.build();
        onChanged();
      } else {
        subscriptionBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * The subscription the add-on was applied to. May only contain the add-on's
     * UUID in some circumstances.
     * </pre>
     *
     * <code>.qms.Subscription subscription = 3;</code>
     */
    public Builder mergeSubscription(org.cyverse.de.protobufs.Subscription value) {
      if (subscriptionBuilder_ == null) {
        if (subscription_ != null) {
          subscription_ =
            org.cyverse.de.protobufs.Subscription.newBuilder(subscription_).mergeFrom(value).buildPartial();
        } else {
          subscription_ = value;
        }
        onChanged();
      } else {
        subscriptionBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * The subscription the add-on was applied to. May only contain the add-on's
     * UUID in some circumstances.
     * </pre>
     *
     * <code>.qms.Subscription subscription = 3;</code>
     */
    public Builder clearSubscription() {
      if (subscriptionBuilder_ == null) {
        subscription_ = null;
        onChanged();
      } else {
        subscription_ = null;
        subscriptionBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * The subscription the add-on was applied to. May only contain the add-on's
     * UUID in some circumstances.
     * </pre>
     *
     * <code>.qms.Subscription subscription = 3;</code>
     */
    public org.cyverse.de.protobufs.Subscription.Builder getSubscriptionBuilder() {
      
      onChanged();
      return getSubscriptionFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * The subscription the add-on was applied to. May only contain the add-on's
     * UUID in some circumstances.
     * </pre>
     *
     * <code>.qms.Subscription subscription = 3;</code>
     */
    public org.cyverse.de.protobufs.SubscriptionOrBuilder getSubscriptionOrBuilder() {
      if (subscriptionBuilder_ != null) {
        return subscriptionBuilder_.getMessageOrBuilder();
      } else {
        return subscription_ == null ?
            org.cyverse.de.protobufs.Subscription.getDefaultInstance() : subscription_;
      }
    }
    /**
     * <pre>
     * The subscription the add-on was applied to. May only contain the add-on's
     * UUID in some circumstances.
     * </pre>
     *
     * <code>.qms.Subscription subscription = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.cyverse.de.protobufs.Subscription, org.cyverse.de.protobufs.Subscription.Builder, org.cyverse.de.protobufs.SubscriptionOrBuilder> 
        getSubscriptionFieldBuilder() {
      if (subscriptionBuilder_ == null) {
        subscriptionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.cyverse.de.protobufs.Subscription, org.cyverse.de.protobufs.Subscription.Builder, org.cyverse.de.protobufs.SubscriptionOrBuilder>(
                getSubscription(),
                getParentForChildren(),
                isClean());
        subscription_ = null;
      }
      return subscriptionBuilder_;
    }

    private double amount_ ;
    /**
     * <pre>
     * The amount of the resource applied by the add-on. This should default to
     * the amount contained in the add-on definition, but can be overridden, 
     * which is why it's a separate field here.
     * </pre>
     *
     * <code>double amount = 4;</code>
     * @return The amount.
     */
    @java.lang.Override
    public double getAmount() {
      return amount_;
    }
    /**
     * <pre>
     * The amount of the resource applied by the add-on. This should default to
     * the amount contained in the add-on definition, but can be overridden, 
     * which is why it's a separate field here.
     * </pre>
     *
     * <code>double amount = 4;</code>
     * @param value The amount to set.
     * @return This builder for chaining.
     */
    public Builder setAmount(double value) {
      
      amount_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The amount of the resource applied by the add-on. This should default to
     * the amount contained in the add-on definition, but can be overridden, 
     * which is why it's a separate field here.
     * </pre>
     *
     * <code>double amount = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearAmount() {
      
      amount_ = 0D;
      onChanged();
      return this;
    }

    private boolean paid_ ;
    /**
     * <pre>
     * Whether the subscription add-on costs money. This should default to the 
     * same paid value contained in the add-on definition, but can be overridden,
     * which is whay it's a separate field here.
     * </pre>
     *
     * <code>bool paid = 5;</code>
     * @return The paid.
     */
    @java.lang.Override
    public boolean getPaid() {
      return paid_;
    }
    /**
     * <pre>
     * Whether the subscription add-on costs money. This should default to the 
     * same paid value contained in the add-on definition, but can be overridden,
     * which is whay it's a separate field here.
     * </pre>
     *
     * <code>bool paid = 5;</code>
     * @param value The paid to set.
     * @return This builder for chaining.
     */
    public Builder setPaid(boolean value) {
      
      paid_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Whether the subscription add-on costs money. This should default to the 
     * same paid value contained in the add-on definition, but can be overridden,
     * which is whay it's a separate field here.
     * </pre>
     *
     * <code>bool paid = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearPaid() {
      
      paid_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:qms.SubscriptionAddon)
  }

  // @@protoc_insertion_point(class_scope:qms.SubscriptionAddon)
  private static final org.cyverse.de.protobufs.SubscriptionAddon DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.cyverse.de.protobufs.SubscriptionAddon();
  }

  public static org.cyverse.de.protobufs.SubscriptionAddon getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SubscriptionAddon>
      PARSER = new com.google.protobuf.AbstractParser<SubscriptionAddon>() {
    @java.lang.Override
    public SubscriptionAddon parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<SubscriptionAddon> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SubscriptionAddon> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.cyverse.de.protobufs.SubscriptionAddon getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

