// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: qms_usages.proto

package org.cyverse.de.protobufs;

public interface UsageListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UsageList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Contains telemetry information
   * </pre>
   *
   * <code>.Header header = 1;</code>
   * @return Whether the header field is set.
   */
  boolean hasHeader();
  /**
   * <pre>
   * Contains telemetry information
   * </pre>
   *
   * <code>.Header header = 1;</code>
   * @return The header.
   */
  org.cyverse.de.protobufs.Header getHeader();
  /**
   * <pre>
   * Contains telemetry information
   * </pre>
   *
   * <code>.Header header = 1;</code>
   */
  org.cyverse.de.protobufs.HeaderOrBuilder getHeaderOrBuilder();

  /**
   * <pre>
   * Error information returned by the request handler.
   * </pre>
   *
   * <code>.ServiceError error = 2;</code>
   * @return Whether the error field is set.
   */
  boolean hasError();
  /**
   * <pre>
   * Error information returned by the request handler.
   * </pre>
   *
   * <code>.ServiceError error = 2;</code>
   * @return The error.
   */
  org.cyverse.de.protobufs.ServiceError getError();
  /**
   * <pre>
   * Error information returned by the request handler.
   * </pre>
   *
   * <code>.ServiceError error = 2;</code>
   */
  org.cyverse.de.protobufs.ServiceErrorOrBuilder getErrorOrBuilder();

  /**
   * <pre>
   * A list of usages returned by the request handler.
   * </pre>
   *
   * <code>repeated .Usage usages = 3;</code>
   */
  java.util.List<org.cyverse.de.protobufs.Usage> 
      getUsagesList();
  /**
   * <pre>
   * A list of usages returned by the request handler.
   * </pre>
   *
   * <code>repeated .Usage usages = 3;</code>
   */
  org.cyverse.de.protobufs.Usage getUsages(int index);
  /**
   * <pre>
   * A list of usages returned by the request handler.
   * </pre>
   *
   * <code>repeated .Usage usages = 3;</code>
   */
  int getUsagesCount();
  /**
   * <pre>
   * A list of usages returned by the request handler.
   * </pre>
   *
   * <code>repeated .Usage usages = 3;</code>
   */
  java.util.List<? extends org.cyverse.de.protobufs.UsageOrBuilder> 
      getUsagesOrBuilderList();
  /**
   * <pre>
   * A list of usages returned by the request handler.
   * </pre>
   *
   * <code>repeated .Usage usages = 3;</code>
   */
  org.cyverse.de.protobufs.UsageOrBuilder getUsagesOrBuilder(
      int index);
}
