// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: svcerror/svcerror.proto

package svcerror

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Code int32

const (
	Code_INTERNAL    Code = 0
	Code_NOT_FOUND   Code = 1
	Code_BAD_REQUEST Code = 2
)

// Enum value maps for Code.
var (
	Code_name = map[int32]string{
		0: "INTERNAL",
		1: "NOT_FOUND",
		2: "BAD_REQUEST",
	}
	Code_value = map[string]int32{
		"INTERNAL":    0,
		"NOT_FOUND":   1,
		"BAD_REQUEST": 2,
	}
)

func (x Code) Enum() *Code {
	p := new(Code)
	*p = x
	return p
}

func (x Code) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Code) Descriptor() protoreflect.EnumDescriptor {
	return file_svcerror_svcerror_proto_enumTypes[0].Descriptor()
}

func (Code) Type() protoreflect.EnumType {
	return &file_svcerror_svcerror_proto_enumTypes[0]
}

func (x Code) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Code.Descriptor instead.
func (Code) EnumDescriptor() ([]byte, []int) {
	return file_svcerror_svcerror_proto_rawDescGZIP(), []int{0}
}

type Error struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrorCode Code       `protobuf:"varint,1,opt,name=ErrorCode,proto3,enum=Code" json:"ErrorCode,omitempty"`
	Message   string     `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	Details   *anypb.Any `protobuf:"bytes,3,opt,name=Details,proto3" json:"Details,omitempty"`
}

func (x *Error) Reset() {
	*x = Error{}
	if protoimpl.UnsafeEnabled {
		mi := &file_svcerror_svcerror_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_svcerror_svcerror_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_svcerror_svcerror_proto_rawDescGZIP(), []int{0}
}

func (x *Error) GetErrorCode() Code {
	if x != nil {
		return x.ErrorCode
	}
	return Code_INTERNAL
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Error) GetDetails() *anypb.Any {
	if x != nil {
		return x.Details
	}
	return nil
}

var File_svcerror_svcerror_proto protoreflect.FileDescriptor

var file_svcerror_svcerror_proto_rawDesc = []byte{
	0x0a, 0x17, 0x73, 0x76, 0x63, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x2f, 0x73, 0x76, 0x63, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x19, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x61, 0x6e, 0x79, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x76, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x23, 0x0a,
	0x09, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x05, 0x2e, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x09, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f,
	0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x2e, 0x0a, 0x07,
	0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x41, 0x6e, 0x79, 0x52, 0x07, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x2a, 0x34, 0x0a, 0x04,
	0x43, 0x6f, 0x64, 0x65, 0x12, 0x0c, 0x0a, 0x08, 0x49, 0x4e, 0x54, 0x45, 0x52, 0x4e, 0x41, 0x4c,
	0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x4e, 0x4f, 0x54, 0x5f, 0x46, 0x4f, 0x55, 0x4e, 0x44, 0x10,
	0x01, 0x12, 0x0f, 0x0a, 0x0b, 0x42, 0x41, 0x44, 0x5f, 0x52, 0x45, 0x51, 0x55, 0x45, 0x53, 0x54,
	0x10, 0x02, 0x42, 0x25, 0x5a, 0x23, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x63, 0x79, 0x76, 0x65, 0x72, 0x73, 0x65, 0x2d, 0x64, 0x65, 0x2f, 0x70, 0x2f, 0x67, 0x6f,
	0x2f, 0x73, 0x76, 0x63, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_svcerror_svcerror_proto_rawDescOnce sync.Once
	file_svcerror_svcerror_proto_rawDescData = file_svcerror_svcerror_proto_rawDesc
)

func file_svcerror_svcerror_proto_rawDescGZIP() []byte {
	file_svcerror_svcerror_proto_rawDescOnce.Do(func() {
		file_svcerror_svcerror_proto_rawDescData = protoimpl.X.CompressGZIP(file_svcerror_svcerror_proto_rawDescData)
	})
	return file_svcerror_svcerror_proto_rawDescData
}

var file_svcerror_svcerror_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_svcerror_svcerror_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_svcerror_svcerror_proto_goTypes = []interface{}{
	(Code)(0),         // 0: Code
	(*Error)(nil),     // 1: Error
	(*anypb.Any)(nil), // 2: google.protobuf.Any
}
var file_svcerror_svcerror_proto_depIdxs = []int32{
	0, // 0: Error.ErrorCode:type_name -> Code
	2, // 1: Error.Details:type_name -> google.protobuf.Any
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_svcerror_svcerror_proto_init() }
func file_svcerror_svcerror_proto_init() {
	if File_svcerror_svcerror_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_svcerror_svcerror_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Error); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_svcerror_svcerror_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_svcerror_svcerror_proto_goTypes,
		DependencyIndexes: file_svcerror_svcerror_proto_depIdxs,
		EnumInfos:         file_svcerror_svcerror_proto_enumTypes,
		MessageInfos:      file_svcerror_svcerror_proto_msgTypes,
	}.Build()
	File_svcerror_svcerror_proto = out.File
	file_svcerror_svcerror_proto_rawDesc = nil
	file_svcerror_svcerror_proto_goTypes = nil
	file_svcerror_svcerror_proto_depIdxs = nil
}
